import React from "react";
import { AiContentGenerate, type AiQuestionResponse } from "./AiContentGenerate";
import { homeworkApi } from "@/lib/api/homework";
import { toast } from "sonner";

interface AiHomeworkGenerateProps {
  lockedClass?: { id: string; name: string; level: string } | null;
  onDone?: (title: string, classId?: string) => void;
}

export const AiHomeworkGenerate: React.FC<AiHomeworkGenerateProps> = ({
  lockedClass,
  onDone,
}) => {
  return (
    <AiContentGenerate
      config={{
        title: "AI Generate Homework",
        subtitle:
          "Select a lesson and AI will generate homework questions from the content library.",
        generateApi: async (req) => {
          const res = await homeworkApi.generateAiHomework(req);
          return res as unknown as AiQuestionResponse;
        },
        metadataFields: [
          {
            key: "dueDate",
            label: "Due date",
            type: "datetime-local",
          },
          {
            key: "maxScore",
            label: "Max score",
            type: "number",
            defaultValue: 100,
          },
          {
            key: "attempts",
            label: "Attempts allowed",
            type: "number",
            defaultValue: 2,
          },
        ],
        onSave: async ({ questions, classId, title, shouldPublish, metadata, createQuestion, queryClient }) => {
          const savedQuestionIds: string[] = [];
          for (const q of questions) {
            const res = await createQuestion(q);
            savedQuestionIds.push(res.id);
          }

          const hwTitle = title || "AI Generated Homework";
          await homeworkApi.createHomework({
            classId,
            title: hwTitle,
            instructions: "Generated by AI from lesson content.",
            dueDate: (metadata.dueDate as string) || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
            maxScore: (metadata.maxScore as number) || 100,
            attempts: (metadata.attempts as number) || 2,
            timeLimit: (metadata.duration as number) || 60,
            questionIds: savedQuestionIds,
            status: shouldPublish ? "ASSIGNED" : "DRAFT",
          });

          await Promise.all([
            queryClient.invalidateQueries({ queryKey: ["teacherHomeworksByClass", classId] }),
            queryClient.invalidateQueries({ queryKey: ["teacherClasses"] }),
          ]);

          if (onDone) {
            onDone(hwTitle, classId);
          }
        },
        onDone,
      }}
      lockedClass={lockedClass}
    />
  );
};
