package com.midori.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Hanabira-sourced JLPT grammar pattern.
 * Separate from {@link Grammar} (teacher-authored content).
 * Vietnamese translation is generated lazily via Gemini AI and permanently cached here.
 */
@Entity
@Table(name = "grammar_patterns")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GrammarPattern {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Grammar pattern string, e.g. "～ています". Unique — used for deduplication on re-import. */
    @Column(nullable = false, length = 500, unique = true)
    private String pattern;

    /** JLPT level: N5, N4, N3, N2, N1 */
    @Column(name = "jlpt_level", length = 10)
    private String jlptLevel;

    // ── English content (from Hanabira JSON) ──────────────────────────────────

    @Column(name = "meaning_en", columnDefinition = "TEXT")
    private String meaningEn;

    @Column(name = "description_en", columnDefinition = "TEXT")
    private String descriptionEn;

    // ── Vietnamese content (generated by Gemini AI, saved once) ───────────────

    @Column(name = "meaning_vi", columnDefinition = "TEXT")
    private String meaningVi;

    @Column(name = "description_vi", columnDefinition = "TEXT")
    private String descriptionVi;

    // ── Structure ──────────────────────────────────────────────────────────────

    @Column(name = "structure", columnDefinition = "TEXT")
    private String structure;

    // ── Example ───────────────────────────────────────────────────────────────

    @Column(name = "example_japanese", columnDefinition = "TEXT")
    private String exampleJapanese;

    @Column(name = "example_english", columnDefinition = "TEXT")
    private String exampleEnglish;

    @Column(name = "example_vietnamese", columnDefinition = "TEXT")
    private String exampleVietnamese;

    // ── Note ──────────────────────────────────────────────────────────────────

    @Column(name = "note", columnDefinition = "TEXT")
    private String note;

    // ── Status ────────────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private GrammarPatternStatus status = GrammarPatternStatus.PENDING_TRANSLATION;

    // ── Timestamps ────────────────────────────────────────────────────────────

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Column(name = "translated_at")
    private Instant translatedAt;
}
