/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TeacherPendingRouteImport } from './routes/teacher-pending'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetSuccessRouteImport } from './routes/reset-success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherVocabularyRouteImport } from './routes/teacher.vocabulary'
import { Route as TeacherShadowingRouteImport } from './routes/teacher.shadowing'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherListeningRouteImport } from './routes/teacher.listening'
import { Route as TeacherGrammarRouteImport } from './routes/teacher.grammar'
import { Route as TeacherFlashcardsRouteImport } from './routes/teacher.flashcards'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as StudentVocabularyRouteImport } from './routes/student.vocabulary'
import { Route as StudentShadowingRouteImport } from './routes/student.shadowing'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentListeningRouteImport } from './routes/student.listening'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentJlptRouteImport } from './routes/student.jlpt'
import { Route as StudentGrammarRouteImport } from './routes/student.grammar'
import { Route as StudentFlashcardsRouteImport } from './routes/student.flashcards'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentAiSenseiRouteImport } from './routes/student.ai-sensei'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminGrammarApprovalRouteImport } from './routes/admin.grammar-approval'
import { Route as AdminGrammarRouteImport } from './routes/admin.grammar'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminContentApprovalRouteImport } from './routes/admin.content-approval'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as TeacherVocabularyLessonIdRouteImport } from './routes/teacher.vocabulary.$lessonId'
import { Route as StudentVocabularyLessonIdRouteImport } from './routes/student.vocabulary.$lessonId'
import { Route as StudentGrammarIndexRouteImport } from './routes/student.grammar._index'
import { Route as StudentGrammarGrammarIdRouteImport } from './routes/student.grammar.$grammarId'
import { Route as StudentGrammarGrammarIdStructureIdRouteImport } from './routes/student.grammar.$grammarId.$structureId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPendingRoute = TeacherPendingRouteImport.update({
  id: '/teacher-pending',
  path: '/teacher-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSuccessRoute = ResetSuccessRouteImport.update({
  id: '/reset-success',
  path: '/reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyRoute = TeacherVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherShadowingRoute = TeacherShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherListeningRoute = TeacherListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGrammarRoute = TeacherGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFlashcardsRoute = TeacherFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentShadowingRoute = StudentShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJlptRoute = StudentJlptRouteImport.update({
  id: '/jlpt',
  path: '/jlpt',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGrammarRoute = StudentGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlashcardsRoute = StudentFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiSenseiRoute = StudentAiSenseiRouteImport.update({
  id: '/ai-sensei',
  path: '/ai-sensei',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrammarApprovalRoute = AdminGrammarApprovalRouteImport.update({
  id: '/grammar-approval',
  path: '/grammar-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrammarRoute = AdminGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalRoute = AdminContentApprovalRouteImport.update({
  id: '/content-approval',
  path: '/content-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyLessonIdRoute =
  TeacherVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => TeacherVocabularyRoute,
  } as any)
const StudentVocabularyLessonIdRoute =
  StudentVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => StudentVocabularyRoute,
  } as any)
const StudentGrammarIndexRoute = StudentGrammarIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const StudentGrammarGrammarIdRoute = StudentGrammarGrammarIdRouteImport.update({
  id: '/$grammarId',
  path: '/$grammarId',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const StudentGrammarGrammarIdStructureIdRoute =
  StudentGrammarGrammarIdStructureIdRouteImport.update({
    id: '/$structureId',
    path: '/$structureId',
    getParentRoute: () => StudentGrammarGrammarIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/grammar/_index': typeof StudentGrammarIndexRoute
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/grammar/$grammarId'
    | '/student/grammar/_index'
    | '/student/vocabulary/$lessonId'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetSuccessRoute: typeof ResetSuccessRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherPendingRoute: typeof TeacherPendingRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-pending': {
      id: '/teacher-pending'
      path: '/teacher-pending'
      fullPath: '/teacher-pending'
      preLoaderRoute: typeof TeacherPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-success': {
      id: '/reset-success'
      path: '/reset-success'
      fullPath: '/reset-success'
      preLoaderRoute: typeof ResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary': {
      id: '/teacher/vocabulary'
      path: '/vocabulary'
      fullPath: '/teacher/vocabulary'
      preLoaderRoute: typeof TeacherVocabularyRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/shadowing': {
      id: '/teacher/shadowing'
      path: '/shadowing'
      fullPath: '/teacher/shadowing'
      preLoaderRoute: typeof TeacherShadowingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/listening': {
      id: '/teacher/listening'
      path: '/listening'
      fullPath: '/teacher/listening'
      preLoaderRoute: typeof TeacherListeningRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grammar': {
      id: '/teacher/grammar'
      path: '/grammar'
      fullPath: '/teacher/grammar'
      preLoaderRoute: typeof TeacherGrammarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/flashcards': {
      id: '/teacher/flashcards'
      path: '/flashcards'
      fullPath: '/teacher/flashcards'
      preLoaderRoute: typeof TeacherFlashcardsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/shadowing': {
      id: '/student/shadowing'
      path: '/shadowing'
      fullPath: '/student/shadowing'
      preLoaderRoute: typeof StudentShadowingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/jlpt': {
      id: '/student/jlpt'
      path: '/jlpt'
      fullPath: '/student/jlpt'
      preLoaderRoute: typeof StudentJlptRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grammar': {
      id: '/student/grammar'
      path: '/grammar'
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flashcards': {
      id: '/student/flashcards'
      path: '/flashcards'
      fullPath: '/student/flashcards'
      preLoaderRoute: typeof StudentFlashcardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-sensei': {
      id: '/student/ai-sensei'
      path: '/ai-sensei'
      fullPath: '/student/ai-sensei'
      preLoaderRoute: typeof StudentAiSenseiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grammar-approval': {
      id: '/admin/grammar-approval'
      path: '/grammar-approval'
      fullPath: '/admin/grammar-approval'
      preLoaderRoute: typeof AdminGrammarApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grammar': {
      id: '/admin/grammar'
      path: '/grammar'
      fullPath: '/admin/grammar'
      preLoaderRoute: typeof AdminGrammarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval': {
      id: '/admin/content-approval'
      path: '/content-approval'
      fullPath: '/admin/content-approval'
      preLoaderRoute: typeof AdminContentApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary/$lessonId': {
      id: '/teacher/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/teacher/vocabulary/$lessonId'
      preLoaderRoute: typeof TeacherVocabularyLessonIdRouteImport
      parentRoute: typeof TeacherVocabularyRoute
    }
    '/student/vocabulary/$lessonId': {
      id: '/student/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/student/vocabulary/$lessonId'
      preLoaderRoute: typeof StudentVocabularyLessonIdRouteImport
      parentRoute: typeof StudentVocabularyRoute
    }
    '/student/grammar/_index': {
      id: '/student/grammar/_index'
      path: ''
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarIndexRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/student/grammar/$grammarId': {
      id: '/student/grammar/$grammarId'
      path: '/$grammarId'
      fullPath: '/student/grammar/$grammarId'
      preLoaderRoute: typeof StudentGrammarGrammarIdRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/student/grammar/$grammarId/$structureId': {
      id: '/student/grammar/$grammarId/$structureId'
      path: '/$structureId'
      fullPath: '/student/grammar/$grammarId/$structureId'
      preLoaderRoute: typeof StudentGrammarGrammarIdStructureIdRouteImport
      parentRoute: typeof StudentGrammarGrammarIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentApprovalRoute: typeof AdminContentApprovalRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminGrammarRoute: typeof AdminGrammarRoute
  AdminGrammarApprovalRoute: typeof AdminGrammarApprovalRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentApprovalRoute: AdminContentApprovalRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminGrammarRoute: AdminGrammarRoute,
  AdminGrammarApprovalRoute: AdminGrammarApprovalRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentGrammarGrammarIdRouteChildren {
  StudentGrammarGrammarIdStructureIdRoute: typeof StudentGrammarGrammarIdStructureIdRoute
}

const StudentGrammarGrammarIdRouteChildren: StudentGrammarGrammarIdRouteChildren =
  {
    StudentGrammarGrammarIdStructureIdRoute:
      StudentGrammarGrammarIdStructureIdRoute,
  }

const StudentGrammarGrammarIdRouteWithChildren =
  StudentGrammarGrammarIdRoute._addFileChildren(
    StudentGrammarGrammarIdRouteChildren,
  )

interface StudentGrammarRouteChildren {
  StudentGrammarGrammarIdRoute: typeof StudentGrammarGrammarIdRouteWithChildren
  StudentGrammarIndexRoute: typeof StudentGrammarIndexRoute
}

const StudentGrammarRouteChildren: StudentGrammarRouteChildren = {
  StudentGrammarGrammarIdRoute: StudentGrammarGrammarIdRouteWithChildren,
  StudentGrammarIndexRoute: StudentGrammarIndexRoute,
}

const StudentGrammarRouteWithChildren = StudentGrammarRoute._addFileChildren(
  StudentGrammarRouteChildren,
)

interface StudentVocabularyRouteChildren {
  StudentVocabularyLessonIdRoute: typeof StudentVocabularyLessonIdRoute
}

const StudentVocabularyRouteChildren: StudentVocabularyRouteChildren = {
  StudentVocabularyLessonIdRoute: StudentVocabularyLessonIdRoute,
}

const StudentVocabularyRouteWithChildren =
  StudentVocabularyRoute._addFileChildren(StudentVocabularyRouteChildren)

interface StudentRouteChildren {
  StudentAiSenseiRoute: typeof StudentAiSenseiRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentFlashcardsRoute: typeof StudentFlashcardsRoute
  StudentGrammarRoute: typeof StudentGrammarRouteWithChildren
  StudentJlptRoute: typeof StudentJlptRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentListeningRoute: typeof StudentListeningRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentShadowingRoute: typeof StudentShadowingRoute
  StudentVocabularyRoute: typeof StudentVocabularyRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiSenseiRoute: StudentAiSenseiRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentFlashcardsRoute: StudentFlashcardsRoute,
  StudentGrammarRoute: StudentGrammarRouteWithChildren,
  StudentJlptRoute: StudentJlptRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentListeningRoute: StudentListeningRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentShadowingRoute: StudentShadowingRoute,
  StudentVocabularyRoute: StudentVocabularyRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherVocabularyRouteChildren {
  TeacherVocabularyLessonIdRoute: typeof TeacherVocabularyLessonIdRoute
}

const TeacherVocabularyRouteChildren: TeacherVocabularyRouteChildren = {
  TeacherVocabularyLessonIdRoute: TeacherVocabularyLessonIdRoute,
}

const TeacherVocabularyRouteWithChildren =
  TeacherVocabularyRoute._addFileChildren(TeacherVocabularyRouteChildren)

interface TeacherRouteChildren {
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherFlashcardsRoute: typeof TeacherFlashcardsRoute
  TeacherGrammarRoute: typeof TeacherGrammarRoute
  TeacherListeningRoute: typeof TeacherListeningRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherShadowingRoute: typeof TeacherShadowingRoute
  TeacherVocabularyRoute: typeof TeacherVocabularyRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherFlashcardsRoute: TeacherFlashcardsRoute,
  TeacherGrammarRoute: TeacherGrammarRoute,
  TeacherListeningRoute: TeacherListeningRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherShadowingRoute: TeacherShadowingRoute,
  TeacherVocabularyRoute: TeacherVocabularyRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetSuccessRoute: ResetSuccessRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherPendingRoute: TeacherPendingRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
