/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TeacherPendingRouteImport } from './routes/teacher-pending'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetSuccessRouteImport } from './routes/reset-success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherVocabularyRouteImport } from './routes/teacher.vocabulary'
import { Route as TeacherShadowingRouteImport } from './routes/teacher.shadowing'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherProgressRouteImport } from './routes/teacher.progress'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherListeningRouteImport } from './routes/teacher.listening'
import { Route as TeacherLessonsRouteImport } from './routes/teacher.lessons'
import { Route as TeacherJlptBankRouteImport } from './routes/teacher.jlpt-bank'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherGrammarRouteImport } from './routes/teacher.grammar'
import { Route as TeacherFlashcardsRouteImport } from './routes/teacher.flashcards'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherDataBankRouteImport } from './routes/teacher.data-bank'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as StudentVocabularyRouteImport } from './routes/student.vocabulary'
import { Route as StudentShadowingRouteImport } from './routes/student.shadowing'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentListeningRouteImport } from './routes/student.listening'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentJlptRouteImport } from './routes/student.jlpt'
import { Route as StudentGrammarRouteImport } from './routes/student.grammar'
import { Route as StudentFlashcardsRouteImport } from './routes/student.flashcards'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentAiSenseiRouteImport } from './routes/student.ai-sensei'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotificationRouteImport } from './routes/admin.notification'
import { Route as TeacherVocabularyLessonIdRouteImport } from './routes/teacher.vocabulary.$lessonId'
import { Route as TeacherLessonsCreateRouteImport } from './routes/teacher.lessons.create'
import { Route as TeacherHomeworkCreateRouteImport } from './routes/teacher.homework.create'
import { Route as TeacherExamsCreateRouteImport } from './routes/teacher.exams.create'
import { Route as TeacherClassesCreateRouteImport } from './routes/teacher.classes.create'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes.$classId'
import { Route as StudentVocabularyLessonIdRouteImport } from './routes/student.vocabulary.$lessonId'
import { Route as StudentGrammarIndexRouteImport } from './routes/student.grammar._index'
import { Route as StudentGrammarGrammarIdRouteImport } from './routes/student.grammar.$grammarId'
import { Route as AdminTeachersTeacherIdRouteImport } from './routes/admin.teachers.$teacherId'
import { Route as AdminQuestionBankQuestionBuilderRouteImport } from './routes/admin.question-bank.question-builder'
import { Route as AdminQuestionBankLessonDetailRouteImport } from './routes/admin.question-bank.lesson-detail'
import { Route as AdminQuestionBankImportExcelRouteImport } from './routes/admin.question-bank.import-excel'
import { Route as AdminQuestionBankIndexRouteImport } from './routes/admin.question-bank._index'
import { Route as AdminQuestionBankLevelRouteImport } from './routes/admin.question-bank.$level'
import { Route as AdminJlptExamIndexRouteImport } from './routes/admin.jlpt-exam._index'
import { Route as AdminContentLibraryIndexRouteImport } from './routes/admin.content-library._index'
import { Route as AdminContentLibraryLevelRouteImport } from './routes/admin.content-library.$level'
import { Route as AdminClassClassIdRouteImport } from './routes/admin.class.$classId'
import { Route as AdminClassManagementIndexRouteImport } from './routes/admin.class-management._index'
import { Route as AdminContentLibraryLevelIndexRouteImport } from './routes/admin.content-library.$level.index'
import { Route as TeacherClassesClassIdStudentsRouteImport } from './routes/teacher.classes.$classId.students'
import { Route as TeacherClassesClassIdProgressRouteImport } from './routes/teacher.classes.$classId.progress'
import { Route as TeacherClassesClassIdLessonsRouteImport } from './routes/teacher.classes.$classId.lessons'
import { Route as TeacherClassesClassIdHomeworkRouteImport } from './routes/teacher.classes.$classId.homework'
import { Route as TeacherClassesClassIdExamsRouteImport } from './routes/teacher.classes.$classId.exams'
import { Route as StudentGrammarGrammarIdStructureIdRouteImport } from './routes/student.grammar.$grammarId.$structureId'
import { Route as AdminTeachersApprovalTeacherIdRouteImport } from './routes/admin.teachers.approval.$teacherId'
import { Route as AdminTeachersTeacherIdClassesRouteImport } from './routes/admin.teachers.$teacherId.classes'
import { Route as AdminTeachersTeacherIdAnalyticsRouteImport } from './routes/admin.teachers.$teacherId.analytics'
import { Route as AdminJlptExamLevelCreateRouteImport } from './routes/admin.jlpt-exam.$level.create'
import { Route as AdminJlptExamLevelIndexRouteImport } from './routes/admin.jlpt-exam.$level._index'
import { Route as AdminJlptExamLevelExamIdEditRouteImport } from './routes/admin.jlpt-exam.$level.$examId.edit'
import { Route as AdminContentLibraryLevelSkillIndexRouteImport } from './routes/admin.content-library.$level.$skill._index'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPendingRoute = TeacherPendingRouteImport.update({
  id: '/teacher-pending',
  path: '/teacher-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSuccessRoute = ResetSuccessRouteImport.update({
  id: '/reset-success',
  path: '/reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyRoute = TeacherVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherShadowingRoute = TeacherShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProgressRoute = TeacherProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherListeningRoute = TeacherListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherJlptBankRoute = TeacherJlptBankRouteImport.update({
  id: '/jlpt-bank',
  path: '/jlpt-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGrammarRoute = TeacherGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFlashcardsRoute = TeacherFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDataBankRoute = TeacherDataBankRouteImport.update({
  id: '/data-bank',
  path: '/data-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentShadowingRoute = StudentShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJlptRoute = StudentJlptRouteImport.update({
  id: '/jlpt',
  path: '/jlpt',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGrammarRoute = StudentGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlashcardsRoute = StudentFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiSenseiRoute = StudentAiSenseiRouteImport.update({
  id: '/ai-sensei',
  path: '/ai-sensei',
  getParentRoute: () => StudentRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationRoute = AdminNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyLessonIdRoute =
  TeacherVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => TeacherVocabularyRoute,
  } as any)
const TeacherLessonsCreateRoute = TeacherLessonsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherLessonsRoute,
} as any)
const TeacherHomeworkCreateRoute = TeacherHomeworkCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherHomeworkRoute,
} as any)
const TeacherExamsCreateRoute = TeacherExamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherExamsRoute,
} as any)
const TeacherClassesCreateRoute = TeacherClassesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherClassesRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => TeacherClassesRoute,
} as any)
const StudentVocabularyLessonIdRoute =
  StudentVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => StudentVocabularyRoute,
  } as any)
const StudentGrammarIndexRoute = StudentGrammarIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const StudentGrammarGrammarIdRoute = StudentGrammarGrammarIdRouteImport.update({
  id: '/$grammarId',
  path: '/$grammarId',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const AdminTeachersTeacherIdRoute = AdminTeachersTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => AdminTeachersRoute,
} as any)
const AdminQuestionBankQuestionBuilderRoute =
  AdminQuestionBankQuestionBuilderRouteImport.update({
    id: '/question-bank/question-builder',
    path: '/question-bank/question-builder',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminQuestionBankLessonDetailRoute =
  AdminQuestionBankLessonDetailRouteImport.update({
    id: '/question-bank/lesson-detail',
    path: '/question-bank/lesson-detail',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminQuestionBankImportExcelRoute =
  AdminQuestionBankImportExcelRouteImport.update({
    id: '/question-bank/import-excel',
    path: '/question-bank/import-excel',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminQuestionBankIndexRoute = AdminQuestionBankIndexRouteImport.update({
  id: '/question-bank/_index',
  path: '/question-bank',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionBankLevelRoute = AdminQuestionBankLevelRouteImport.update({
  id: '/question-bank/$level',
  path: '/question-bank/$level',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJlptExamIndexRoute = AdminJlptExamIndexRouteImport.update({
  id: '/jlpt-exam/_index',
  path: '/jlpt-exam',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentLibraryIndexRoute =
  AdminContentLibraryIndexRouteImport.update({
    id: '/content-library/_index',
    path: '/content-library',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentLibraryLevelRoute =
  AdminContentLibraryLevelRouteImport.update({
    id: '/content-library/$level',
    path: '/content-library/$level',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClassClassIdRoute = AdminClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassManagementIndexRoute =
  AdminClassManagementIndexRouteImport.update({
    id: '/class-management/_index',
    path: '/class-management',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentLibraryLevelIndexRoute =
  AdminContentLibraryLevelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentLibraryLevelRoute,
  } as any)
const TeacherClassesClassIdStudentsRoute =
  TeacherClassesClassIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdProgressRoute =
  TeacherClassesClassIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdLessonsRoute =
  TeacherClassesClassIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdHomeworkRoute =
  TeacherClassesClassIdHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdExamsRoute =
  TeacherClassesClassIdExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const StudentGrammarGrammarIdStructureIdRoute =
  StudentGrammarGrammarIdStructureIdRouteImport.update({
    id: '/$structureId',
    path: '/$structureId',
    getParentRoute: () => StudentGrammarGrammarIdRoute,
  } as any)
const AdminTeachersApprovalTeacherIdRoute =
  AdminTeachersApprovalTeacherIdRouteImport.update({
    id: '/approval/$teacherId',
    path: '/approval/$teacherId',
    getParentRoute: () => AdminTeachersRoute,
  } as any)
const AdminTeachersTeacherIdClassesRoute =
  AdminTeachersTeacherIdClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AdminTeachersTeacherIdRoute,
  } as any)
const AdminTeachersTeacherIdAnalyticsRoute =
  AdminTeachersTeacherIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminTeachersTeacherIdRoute,
  } as any)
const AdminJlptExamLevelCreateRoute =
  AdminJlptExamLevelCreateRouteImport.update({
    id: '/jlpt-exam/$level/create',
    path: '/jlpt-exam/$level/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminJlptExamLevelIndexRoute = AdminJlptExamLevelIndexRouteImport.update({
  id: '/jlpt-exam/$level/_index',
  path: '/jlpt-exam/$level',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJlptExamLevelExamIdEditRoute =
  AdminJlptExamLevelExamIdEditRouteImport.update({
    id: '/jlpt-exam/$level/$examId/edit',
    path: '/jlpt-exam/$level/$examId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentLibraryLevelSkillIndexRoute =
  AdminContentLibraryLevelSkillIndexRouteImport.update({
    id: '/$skill/_index',
    path: '/$skill',
    getParentRoute: () => AdminContentLibraryLevelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/class-management': typeof AdminClassManagementIndexRoute
  '/admin/class/$classId': typeof AdminClassClassIdRoute
  '/admin/content-library/$level': typeof AdminContentLibraryLevelRouteWithChildren
  '/admin/content-library': typeof AdminContentLibraryIndexRoute
  '/admin/jlpt-exam': typeof AdminJlptExamIndexRoute
  '/admin/question-bank/$level': typeof AdminQuestionBankLevelRoute
  '/admin/question-bank': typeof AdminQuestionBankIndexRoute
  '/admin/question-bank/import-excel': typeof AdminQuestionBankImportExcelRoute
  '/admin/question-bank/lesson-detail': typeof AdminQuestionBankLessonDetailRoute
  '/admin/question-bank/question-builder': typeof AdminQuestionBankQuestionBuilderRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRouteWithChildren
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/admin/jlpt-exam/$level': typeof AdminJlptExamLevelIndexRoute
  '/admin/jlpt-exam/$level/create': typeof AdminJlptExamLevelCreateRoute
  '/admin/teachers/$teacherId/analytics': typeof AdminTeachersTeacherIdAnalyticsRoute
  '/admin/teachers/$teacherId/classes': typeof AdminTeachersTeacherIdClassesRoute
  '/admin/teachers/approval/$teacherId': typeof AdminTeachersApprovalTeacherIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
  '/admin/content-library/$level/': typeof AdminContentLibraryLevelIndexRoute
  '/admin/content-library/$level/$skill': typeof AdminContentLibraryLevelSkillIndexRoute
  '/admin/jlpt-exam/$level/$examId/edit': typeof AdminJlptExamLevelExamIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/class-management': typeof AdminClassManagementIndexRoute
  '/admin/class/$classId': typeof AdminClassClassIdRoute
  '/admin/content-library': typeof AdminContentLibraryIndexRoute
  '/admin/jlpt-exam': typeof AdminJlptExamIndexRoute
  '/admin/question-bank/$level': typeof AdminQuestionBankLevelRoute
  '/admin/question-bank': typeof AdminQuestionBankIndexRoute
  '/admin/question-bank/import-excel': typeof AdminQuestionBankImportExcelRoute
  '/admin/question-bank/lesson-detail': typeof AdminQuestionBankLessonDetailRoute
  '/admin/question-bank/question-builder': typeof AdminQuestionBankQuestionBuilderRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRouteWithChildren
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/admin/jlpt-exam/$level': typeof AdminJlptExamLevelIndexRoute
  '/admin/jlpt-exam/$level/create': typeof AdminJlptExamLevelCreateRoute
  '/admin/teachers/$teacherId/analytics': typeof AdminTeachersTeacherIdAnalyticsRoute
  '/admin/teachers/$teacherId/classes': typeof AdminTeachersTeacherIdClassesRoute
  '/admin/teachers/approval/$teacherId': typeof AdminTeachersApprovalTeacherIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
  '/admin/content-library/$level': typeof AdminContentLibraryLevelIndexRoute
  '/admin/content-library/$level/$skill': typeof AdminContentLibraryLevelSkillIndexRoute
  '/admin/jlpt-exam/$level/$examId/edit': typeof AdminJlptExamLevelExamIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/class-management/_index': typeof AdminClassManagementIndexRoute
  '/admin/class/$classId': typeof AdminClassClassIdRoute
  '/admin/content-library/$level': typeof AdminContentLibraryLevelRouteWithChildren
  '/admin/content-library/_index': typeof AdminContentLibraryIndexRoute
  '/admin/jlpt-exam/_index': typeof AdminJlptExamIndexRoute
  '/admin/question-bank/$level': typeof AdminQuestionBankLevelRoute
  '/admin/question-bank/_index': typeof AdminQuestionBankIndexRoute
  '/admin/question-bank/import-excel': typeof AdminQuestionBankImportExcelRoute
  '/admin/question-bank/lesson-detail': typeof AdminQuestionBankLessonDetailRoute
  '/admin/question-bank/question-builder': typeof AdminQuestionBankQuestionBuilderRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRouteWithChildren
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/grammar/_index': typeof StudentGrammarIndexRoute
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/admin/jlpt-exam/$level/_index': typeof AdminJlptExamLevelIndexRoute
  '/admin/jlpt-exam/$level/create': typeof AdminJlptExamLevelCreateRoute
  '/admin/teachers/$teacherId/analytics': typeof AdminTeachersTeacherIdAnalyticsRoute
  '/admin/teachers/$teacherId/classes': typeof AdminTeachersTeacherIdClassesRoute
  '/admin/teachers/approval/$teacherId': typeof AdminTeachersApprovalTeacherIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
  '/admin/content-library/$level/': typeof AdminContentLibraryLevelIndexRoute
  '/admin/content-library/$level/$skill/_index': typeof AdminContentLibraryLevelSkillIndexRoute
  '/admin/jlpt-exam/$level/$examId/edit': typeof AdminJlptExamLevelExamIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/notification'
    | '/admin/profile'
    | '/admin/teachers'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/class-management'
    | '/admin/class/$classId'
    | '/admin/content-library/$level'
    | '/admin/content-library'
    | '/admin/jlpt-exam'
    | '/admin/question-bank/$level'
    | '/admin/question-bank'
    | '/admin/question-bank/import-excel'
    | '/admin/question-bank/lesson-detail'
    | '/admin/question-bank/question-builder'
    | '/admin/teachers/$teacherId'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/admin/jlpt-exam/$level'
    | '/admin/jlpt-exam/$level/create'
    | '/admin/teachers/$teacherId/analytics'
    | '/admin/teachers/$teacherId/classes'
    | '/admin/teachers/approval/$teacherId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
    | '/admin/content-library/$level/'
    | '/admin/content-library/$level/$skill'
    | '/admin/jlpt-exam/$level/$examId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/notification'
    | '/admin/profile'
    | '/admin/teachers'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/class-management'
    | '/admin/class/$classId'
    | '/admin/content-library'
    | '/admin/jlpt-exam'
    | '/admin/question-bank/$level'
    | '/admin/question-bank'
    | '/admin/question-bank/import-excel'
    | '/admin/question-bank/lesson-detail'
    | '/admin/question-bank/question-builder'
    | '/admin/teachers/$teacherId'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/admin/jlpt-exam/$level'
    | '/admin/jlpt-exam/$level/create'
    | '/admin/teachers/$teacherId/analytics'
    | '/admin/teachers/$teacherId/classes'
    | '/admin/teachers/approval/$teacherId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
    | '/admin/content-library/$level'
    | '/admin/content-library/$level/$skill'
    | '/admin/jlpt-exam/$level/$examId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/notification'
    | '/admin/profile'
    | '/admin/teachers'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/admin/class-management/_index'
    | '/admin/class/$classId'
    | '/admin/content-library/$level'
    | '/admin/content-library/_index'
    | '/admin/jlpt-exam/_index'
    | '/admin/question-bank/$level'
    | '/admin/question-bank/_index'
    | '/admin/question-bank/import-excel'
    | '/admin/question-bank/lesson-detail'
    | '/admin/question-bank/question-builder'
    | '/admin/teachers/$teacherId'
    | '/student/grammar/$grammarId'
    | '/student/grammar/_index'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/admin/jlpt-exam/$level/_index'
    | '/admin/jlpt-exam/$level/create'
    | '/admin/teachers/$teacherId/analytics'
    | '/admin/teachers/$teacherId/classes'
    | '/admin/teachers/approval/$teacherId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
    | '/admin/content-library/$level/'
    | '/admin/content-library/$level/$skill/_index'
    | '/admin/jlpt-exam/$level/$examId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetSuccessRoute: typeof ResetSuccessRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherPendingRoute: typeof TeacherPendingRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-pending': {
      id: '/teacher-pending'
      path: '/teacher-pending'
      fullPath: '/teacher-pending'
      preLoaderRoute: typeof TeacherPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-success': {
      id: '/reset-success'
      path: '/reset-success'
      fullPath: '/reset-success'
      preLoaderRoute: typeof ResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary': {
      id: '/teacher/vocabulary'
      path: '/vocabulary'
      fullPath: '/teacher/vocabulary'
      preLoaderRoute: typeof TeacherVocabularyRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/shadowing': {
      id: '/teacher/shadowing'
      path: '/shadowing'
      fullPath: '/teacher/shadowing'
      preLoaderRoute: typeof TeacherShadowingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/question-bank': {
      id: '/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof TeacherQuestionBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/progress': {
      id: '/teacher/progress'
      path: '/progress'
      fullPath: '/teacher/progress'
      preLoaderRoute: typeof TeacherProgressRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/listening': {
      id: '/teacher/listening'
      path: '/listening'
      fullPath: '/teacher/listening'
      preLoaderRoute: typeof TeacherListeningRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/jlpt-bank': {
      id: '/teacher/jlpt-bank'
      path: '/jlpt-bank'
      fullPath: '/teacher/jlpt-bank'
      preLoaderRoute: typeof TeacherJlptBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grammar': {
      id: '/teacher/grammar'
      path: '/grammar'
      fullPath: '/teacher/grammar'
      preLoaderRoute: typeof TeacherGrammarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/flashcards': {
      id: '/teacher/flashcards'
      path: '/flashcards'
      fullPath: '/teacher/flashcards'
      preLoaderRoute: typeof TeacherFlashcardsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/data-bank': {
      id: '/teacher/data-bank'
      path: '/data-bank'
      fullPath: '/teacher/data-bank'
      preLoaderRoute: typeof TeacherDataBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/shadowing': {
      id: '/student/shadowing'
      path: '/shadowing'
      fullPath: '/student/shadowing'
      preLoaderRoute: typeof StudentShadowingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/jlpt': {
      id: '/student/jlpt'
      path: '/jlpt'
      fullPath: '/student/jlpt'
      preLoaderRoute: typeof StudentJlptRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grammar': {
      id: '/student/grammar'
      path: '/grammar'
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flashcards': {
      id: '/student/flashcards'
      path: '/flashcards'
      fullPath: '/student/flashcards'
      preLoaderRoute: typeof StudentFlashcardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-sensei': {
      id: '/student/ai-sensei'
      path: '/ai-sensei'
      fullPath: '/student/ai-sensei'
      preLoaderRoute: typeof StudentAiSenseiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification': {
      id: '/admin/notification'
      path: '/notification'
      fullPath: '/admin/notification'
      preLoaderRoute: typeof AdminNotificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary/$lessonId': {
      id: '/teacher/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/teacher/vocabulary/$lessonId'
      preLoaderRoute: typeof TeacherVocabularyLessonIdRouteImport
      parentRoute: typeof TeacherVocabularyRoute
    }
    '/teacher/lessons/create': {
      id: '/teacher/lessons/create'
      path: '/create'
      fullPath: '/teacher/lessons/create'
      preLoaderRoute: typeof TeacherLessonsCreateRouteImport
      parentRoute: typeof TeacherLessonsRoute
    }
    '/teacher/homework/create': {
      id: '/teacher/homework/create'
      path: '/create'
      fullPath: '/teacher/homework/create'
      preLoaderRoute: typeof TeacherHomeworkCreateRouteImport
      parentRoute: typeof TeacherHomeworkRoute
    }
    '/teacher/exams/create': {
      id: '/teacher/exams/create'
      path: '/create'
      fullPath: '/teacher/exams/create'
      preLoaderRoute: typeof TeacherExamsCreateRouteImport
      parentRoute: typeof TeacherExamsRoute
    }
    '/teacher/classes/create': {
      id: '/teacher/classes/create'
      path: '/create'
      fullPath: '/teacher/classes/create'
      preLoaderRoute: typeof TeacherClassesCreateRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
    '/student/vocabulary/$lessonId': {
      id: '/student/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/student/vocabulary/$lessonId'
      preLoaderRoute: typeof StudentVocabularyLessonIdRouteImport
      parentRoute: typeof StudentVocabularyRoute
    }
    '/student/grammar/_index': {
      id: '/student/grammar/_index'
      path: ''
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarIndexRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/student/grammar/$grammarId': {
      id: '/student/grammar/$grammarId'
      path: '/$grammarId'
      fullPath: '/student/grammar/$grammarId'
      preLoaderRoute: typeof StudentGrammarGrammarIdRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/admin/teachers/$teacherId': {
      id: '/admin/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AdminTeachersTeacherIdRouteImport
      parentRoute: typeof AdminTeachersRoute
    }
    '/admin/question-bank/question-builder': {
      id: '/admin/question-bank/question-builder'
      path: '/question-bank/question-builder'
      fullPath: '/admin/question-bank/question-builder'
      preLoaderRoute: typeof AdminQuestionBankQuestionBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank/lesson-detail': {
      id: '/admin/question-bank/lesson-detail'
      path: '/question-bank/lesson-detail'
      fullPath: '/admin/question-bank/lesson-detail'
      preLoaderRoute: typeof AdminQuestionBankLessonDetailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank/import-excel': {
      id: '/admin/question-bank/import-excel'
      path: '/question-bank/import-excel'
      fullPath: '/admin/question-bank/import-excel'
      preLoaderRoute: typeof AdminQuestionBankImportExcelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank/_index': {
      id: '/admin/question-bank/_index'
      path: '/question-bank'
      fullPath: '/admin/question-bank'
      preLoaderRoute: typeof AdminQuestionBankIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/question-bank/$level': {
      id: '/admin/question-bank/$level'
      path: '/question-bank/$level'
      fullPath: '/admin/question-bank/$level'
      preLoaderRoute: typeof AdminQuestionBankLevelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jlpt-exam/_index': {
      id: '/admin/jlpt-exam/_index'
      path: '/jlpt-exam'
      fullPath: '/admin/jlpt-exam'
      preLoaderRoute: typeof AdminJlptExamIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-library/_index': {
      id: '/admin/content-library/_index'
      path: '/content-library'
      fullPath: '/admin/content-library'
      preLoaderRoute: typeof AdminContentLibraryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-library/$level': {
      id: '/admin/content-library/$level'
      path: '/content-library/$level'
      fullPath: '/admin/content-library/$level'
      preLoaderRoute: typeof AdminContentLibraryLevelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class/$classId': {
      id: '/admin/class/$classId'
      path: '/class/$classId'
      fullPath: '/admin/class/$classId'
      preLoaderRoute: typeof AdminClassClassIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class-management/_index': {
      id: '/admin/class-management/_index'
      path: '/class-management'
      fullPath: '/admin/class-management'
      preLoaderRoute: typeof AdminClassManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-library/$level/': {
      id: '/admin/content-library/$level/'
      path: '/'
      fullPath: '/admin/content-library/$level/'
      preLoaderRoute: typeof AdminContentLibraryLevelIndexRouteImport
      parentRoute: typeof AdminContentLibraryLevelRoute
    }
    '/teacher/classes/$classId/students': {
      id: '/teacher/classes/$classId/students'
      path: '/students'
      fullPath: '/teacher/classes/$classId/students'
      preLoaderRoute: typeof TeacherClassesClassIdStudentsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/progress': {
      id: '/teacher/classes/$classId/progress'
      path: '/progress'
      fullPath: '/teacher/classes/$classId/progress'
      preLoaderRoute: typeof TeacherClassesClassIdProgressRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/lessons': {
      id: '/teacher/classes/$classId/lessons'
      path: '/lessons'
      fullPath: '/teacher/classes/$classId/lessons'
      preLoaderRoute: typeof TeacherClassesClassIdLessonsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/homework': {
      id: '/teacher/classes/$classId/homework'
      path: '/homework'
      fullPath: '/teacher/classes/$classId/homework'
      preLoaderRoute: typeof TeacherClassesClassIdHomeworkRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/exams': {
      id: '/teacher/classes/$classId/exams'
      path: '/exams'
      fullPath: '/teacher/classes/$classId/exams'
      preLoaderRoute: typeof TeacherClassesClassIdExamsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/student/grammar/$grammarId/$structureId': {
      id: '/student/grammar/$grammarId/$structureId'
      path: '/$structureId'
      fullPath: '/student/grammar/$grammarId/$structureId'
      preLoaderRoute: typeof StudentGrammarGrammarIdStructureIdRouteImport
      parentRoute: typeof StudentGrammarGrammarIdRoute
    }
    '/admin/teachers/approval/$teacherId': {
      id: '/admin/teachers/approval/$teacherId'
      path: '/approval/$teacherId'
      fullPath: '/admin/teachers/approval/$teacherId'
      preLoaderRoute: typeof AdminTeachersApprovalTeacherIdRouteImport
      parentRoute: typeof AdminTeachersRoute
    }
    '/admin/teachers/$teacherId/classes': {
      id: '/admin/teachers/$teacherId/classes'
      path: '/classes'
      fullPath: '/admin/teachers/$teacherId/classes'
      preLoaderRoute: typeof AdminTeachersTeacherIdClassesRouteImport
      parentRoute: typeof AdminTeachersTeacherIdRoute
    }
    '/admin/teachers/$teacherId/analytics': {
      id: '/admin/teachers/$teacherId/analytics'
      path: '/analytics'
      fullPath: '/admin/teachers/$teacherId/analytics'
      preLoaderRoute: typeof AdminTeachersTeacherIdAnalyticsRouteImport
      parentRoute: typeof AdminTeachersTeacherIdRoute
    }
    '/admin/jlpt-exam/$level/create': {
      id: '/admin/jlpt-exam/$level/create'
      path: '/jlpt-exam/$level/create'
      fullPath: '/admin/jlpt-exam/$level/create'
      preLoaderRoute: typeof AdminJlptExamLevelCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jlpt-exam/$level/_index': {
      id: '/admin/jlpt-exam/$level/_index'
      path: '/jlpt-exam/$level'
      fullPath: '/admin/jlpt-exam/$level'
      preLoaderRoute: typeof AdminJlptExamLevelIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jlpt-exam/$level/$examId/edit': {
      id: '/admin/jlpt-exam/$level/$examId/edit'
      path: '/jlpt-exam/$level/$examId/edit'
      fullPath: '/admin/jlpt-exam/$level/$examId/edit'
      preLoaderRoute: typeof AdminJlptExamLevelExamIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-library/$level/$skill/_index': {
      id: '/admin/content-library/$level/$skill/_index'
      path: '/$skill'
      fullPath: '/admin/content-library/$level/$skill'
      preLoaderRoute: typeof AdminContentLibraryLevelSkillIndexRouteImport
      parentRoute: typeof AdminContentLibraryLevelRoute
    }
  }
}

interface AdminTeachersTeacherIdRouteChildren {
  AdminTeachersTeacherIdAnalyticsRoute: typeof AdminTeachersTeacherIdAnalyticsRoute
  AdminTeachersTeacherIdClassesRoute: typeof AdminTeachersTeacherIdClassesRoute
}

const AdminTeachersTeacherIdRouteChildren: AdminTeachersTeacherIdRouteChildren =
  {
    AdminTeachersTeacherIdAnalyticsRoute: AdminTeachersTeacherIdAnalyticsRoute,
    AdminTeachersTeacherIdClassesRoute: AdminTeachersTeacherIdClassesRoute,
  }

const AdminTeachersTeacherIdRouteWithChildren =
  AdminTeachersTeacherIdRoute._addFileChildren(
    AdminTeachersTeacherIdRouteChildren,
  )

interface AdminTeachersRouteChildren {
  AdminTeachersTeacherIdRoute: typeof AdminTeachersTeacherIdRouteWithChildren
  AdminTeachersApprovalTeacherIdRoute: typeof AdminTeachersApprovalTeacherIdRoute
}

const AdminTeachersRouteChildren: AdminTeachersRouteChildren = {
  AdminTeachersTeacherIdRoute: AdminTeachersTeacherIdRouteWithChildren,
  AdminTeachersApprovalTeacherIdRoute: AdminTeachersApprovalTeacherIdRoute,
}

const AdminTeachersRouteWithChildren = AdminTeachersRoute._addFileChildren(
  AdminTeachersRouteChildren,
)

interface AdminContentLibraryLevelRouteChildren {
  AdminContentLibraryLevelIndexRoute: typeof AdminContentLibraryLevelIndexRoute
  AdminContentLibraryLevelSkillIndexRoute: typeof AdminContentLibraryLevelSkillIndexRoute
}

const AdminContentLibraryLevelRouteChildren: AdminContentLibraryLevelRouteChildren =
  {
    AdminContentLibraryLevelIndexRoute: AdminContentLibraryLevelIndexRoute,
    AdminContentLibraryLevelSkillIndexRoute:
      AdminContentLibraryLevelSkillIndexRoute,
  }

const AdminContentLibraryLevelRouteWithChildren =
  AdminContentLibraryLevelRoute._addFileChildren(
    AdminContentLibraryLevelRouteChildren,
  )

interface AdminRouteChildren {
  AdminNotificationRoute: typeof AdminNotificationRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTeachersRoute: typeof AdminTeachersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClassManagementIndexRoute: typeof AdminClassManagementIndexRoute
  AdminClassClassIdRoute: typeof AdminClassClassIdRoute
  AdminContentLibraryLevelRoute: typeof AdminContentLibraryLevelRouteWithChildren
  AdminContentLibraryIndexRoute: typeof AdminContentLibraryIndexRoute
  AdminJlptExamIndexRoute: typeof AdminJlptExamIndexRoute
  AdminQuestionBankLevelRoute: typeof AdminQuestionBankLevelRoute
  AdminQuestionBankIndexRoute: typeof AdminQuestionBankIndexRoute
  AdminQuestionBankImportExcelRoute: typeof AdminQuestionBankImportExcelRoute
  AdminQuestionBankLessonDetailRoute: typeof AdminQuestionBankLessonDetailRoute
  AdminQuestionBankQuestionBuilderRoute: typeof AdminQuestionBankQuestionBuilderRoute
  AdminJlptExamLevelIndexRoute: typeof AdminJlptExamLevelIndexRoute
  AdminJlptExamLevelCreateRoute: typeof AdminJlptExamLevelCreateRoute
  AdminJlptExamLevelExamIdEditRoute: typeof AdminJlptExamLevelExamIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNotificationRoute: AdminNotificationRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTeachersRoute: AdminTeachersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminClassManagementIndexRoute: AdminClassManagementIndexRoute,
  AdminClassClassIdRoute: AdminClassClassIdRoute,
  AdminContentLibraryLevelRoute: AdminContentLibraryLevelRouteWithChildren,
  AdminContentLibraryIndexRoute: AdminContentLibraryIndexRoute,
  AdminJlptExamIndexRoute: AdminJlptExamIndexRoute,
  AdminQuestionBankLevelRoute: AdminQuestionBankLevelRoute,
  AdminQuestionBankIndexRoute: AdminQuestionBankIndexRoute,
  AdminQuestionBankImportExcelRoute: AdminQuestionBankImportExcelRoute,
  AdminQuestionBankLessonDetailRoute: AdminQuestionBankLessonDetailRoute,
  AdminQuestionBankQuestionBuilderRoute: AdminQuestionBankQuestionBuilderRoute,
  AdminJlptExamLevelIndexRoute: AdminJlptExamLevelIndexRoute,
  AdminJlptExamLevelCreateRoute: AdminJlptExamLevelCreateRoute,
  AdminJlptExamLevelExamIdEditRoute: AdminJlptExamLevelExamIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentGrammarGrammarIdRouteChildren {
  StudentGrammarGrammarIdStructureIdRoute: typeof StudentGrammarGrammarIdStructureIdRoute
}

const StudentGrammarGrammarIdRouteChildren: StudentGrammarGrammarIdRouteChildren =
  {
    StudentGrammarGrammarIdStructureIdRoute:
      StudentGrammarGrammarIdStructureIdRoute,
  }

const StudentGrammarGrammarIdRouteWithChildren =
  StudentGrammarGrammarIdRoute._addFileChildren(
    StudentGrammarGrammarIdRouteChildren,
  )

interface StudentGrammarRouteChildren {
  StudentGrammarGrammarIdRoute: typeof StudentGrammarGrammarIdRouteWithChildren
  StudentGrammarIndexRoute: typeof StudentGrammarIndexRoute
}

const StudentGrammarRouteChildren: StudentGrammarRouteChildren = {
  StudentGrammarGrammarIdRoute: StudentGrammarGrammarIdRouteWithChildren,
  StudentGrammarIndexRoute: StudentGrammarIndexRoute,
}

const StudentGrammarRouteWithChildren = StudentGrammarRoute._addFileChildren(
  StudentGrammarRouteChildren,
)

interface StudentVocabularyRouteChildren {
  StudentVocabularyLessonIdRoute: typeof StudentVocabularyLessonIdRoute
}

const StudentVocabularyRouteChildren: StudentVocabularyRouteChildren = {
  StudentVocabularyLessonIdRoute: StudentVocabularyLessonIdRoute,
}

const StudentVocabularyRouteWithChildren =
  StudentVocabularyRoute._addFileChildren(StudentVocabularyRouteChildren)

interface StudentRouteChildren {
  StudentAiSenseiRoute: typeof StudentAiSenseiRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentFlashcardsRoute: typeof StudentFlashcardsRoute
  StudentGrammarRoute: typeof StudentGrammarRouteWithChildren
  StudentJlptRoute: typeof StudentJlptRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentListeningRoute: typeof StudentListeningRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentShadowingRoute: typeof StudentShadowingRoute
  StudentVocabularyRoute: typeof StudentVocabularyRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiSenseiRoute: StudentAiSenseiRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentFlashcardsRoute: StudentFlashcardsRoute,
  StudentGrammarRoute: StudentGrammarRouteWithChildren,
  StudentJlptRoute: StudentJlptRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentListeningRoute: StudentListeningRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentShadowingRoute: StudentShadowingRoute,
  StudentVocabularyRoute: StudentVocabularyRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherClassesClassIdRouteChildren {
  TeacherClassesClassIdExamsRoute: typeof TeacherClassesClassIdExamsRoute
  TeacherClassesClassIdHomeworkRoute: typeof TeacherClassesClassIdHomeworkRoute
  TeacherClassesClassIdLessonsRoute: typeof TeacherClassesClassIdLessonsRoute
  TeacherClassesClassIdProgressRoute: typeof TeacherClassesClassIdProgressRoute
  TeacherClassesClassIdStudentsRoute: typeof TeacherClassesClassIdStudentsRoute
}

const TeacherClassesClassIdRouteChildren: TeacherClassesClassIdRouteChildren = {
  TeacherClassesClassIdExamsRoute: TeacherClassesClassIdExamsRoute,
  TeacherClassesClassIdHomeworkRoute: TeacherClassesClassIdHomeworkRoute,
  TeacherClassesClassIdLessonsRoute: TeacherClassesClassIdLessonsRoute,
  TeacherClassesClassIdProgressRoute: TeacherClassesClassIdProgressRoute,
  TeacherClassesClassIdStudentsRoute: TeacherClassesClassIdStudentsRoute,
}

const TeacherClassesClassIdRouteWithChildren =
  TeacherClassesClassIdRoute._addFileChildren(
    TeacherClassesClassIdRouteChildren,
  )

interface TeacherClassesRouteChildren {
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRouteWithChildren
  TeacherClassesCreateRoute: typeof TeacherClassesCreateRoute
}

const TeacherClassesRouteChildren: TeacherClassesRouteChildren = {
  TeacherClassesClassIdRoute: TeacherClassesClassIdRouteWithChildren,
  TeacherClassesCreateRoute: TeacherClassesCreateRoute,
}

const TeacherClassesRouteWithChildren = TeacherClassesRoute._addFileChildren(
  TeacherClassesRouteChildren,
)

interface TeacherExamsRouteChildren {
  TeacherExamsCreateRoute: typeof TeacherExamsCreateRoute
}

const TeacherExamsRouteChildren: TeacherExamsRouteChildren = {
  TeacherExamsCreateRoute: TeacherExamsCreateRoute,
}

const TeacherExamsRouteWithChildren = TeacherExamsRoute._addFileChildren(
  TeacherExamsRouteChildren,
)

interface TeacherHomeworkRouteChildren {
  TeacherHomeworkCreateRoute: typeof TeacherHomeworkCreateRoute
}

const TeacherHomeworkRouteChildren: TeacherHomeworkRouteChildren = {
  TeacherHomeworkCreateRoute: TeacherHomeworkCreateRoute,
}

const TeacherHomeworkRouteWithChildren = TeacherHomeworkRoute._addFileChildren(
  TeacherHomeworkRouteChildren,
)

interface TeacherLessonsRouteChildren {
  TeacherLessonsCreateRoute: typeof TeacherLessonsCreateRoute
}

const TeacherLessonsRouteChildren: TeacherLessonsRouteChildren = {
  TeacherLessonsCreateRoute: TeacherLessonsCreateRoute,
}

const TeacherLessonsRouteWithChildren = TeacherLessonsRoute._addFileChildren(
  TeacherLessonsRouteChildren,
)

interface TeacherVocabularyRouteChildren {
  TeacherVocabularyLessonIdRoute: typeof TeacherVocabularyLessonIdRoute
}

const TeacherVocabularyRouteChildren: TeacherVocabularyRouteChildren = {
  TeacherVocabularyLessonIdRoute: TeacherVocabularyLessonIdRoute,
}

const TeacherVocabularyRouteWithChildren =
  TeacherVocabularyRoute._addFileChildren(TeacherVocabularyRouteChildren)

interface TeacherRouteChildren {
  TeacherClassesRoute: typeof TeacherClassesRouteWithChildren
  TeacherDataBankRoute: typeof TeacherDataBankRoute
  TeacherExamsRoute: typeof TeacherExamsRouteWithChildren
  TeacherFlashcardsRoute: typeof TeacherFlashcardsRoute
  TeacherGrammarRoute: typeof TeacherGrammarRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRouteWithChildren
  TeacherJlptBankRoute: typeof TeacherJlptBankRoute
  TeacherLessonsRoute: typeof TeacherLessonsRouteWithChildren
  TeacherListeningRoute: typeof TeacherListeningRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherProgressRoute: typeof TeacherProgressRoute
  TeacherQuestionBankRoute: typeof TeacherQuestionBankRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherShadowingRoute: typeof TeacherShadowingRoute
  TeacherVocabularyRoute: typeof TeacherVocabularyRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherClassesRoute: TeacherClassesRouteWithChildren,
  TeacherDataBankRoute: TeacherDataBankRoute,
  TeacherExamsRoute: TeacherExamsRouteWithChildren,
  TeacherFlashcardsRoute: TeacherFlashcardsRoute,
  TeacherGrammarRoute: TeacherGrammarRoute,
  TeacherHomeworkRoute: TeacherHomeworkRouteWithChildren,
  TeacherJlptBankRoute: TeacherJlptBankRoute,
  TeacherLessonsRoute: TeacherLessonsRouteWithChildren,
  TeacherListeningRoute: TeacherListeningRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherProgressRoute: TeacherProgressRoute,
  TeacherQuestionBankRoute: TeacherQuestionBankRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherShadowingRoute: TeacherShadowingRoute,
  TeacherVocabularyRoute: TeacherVocabularyRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetSuccessRoute: ResetSuccessRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherPendingRoute: TeacherPendingRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
