/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TeacherPendingRouteImport } from './routes/teacher-pending'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetSuccessRouteImport } from './routes/reset-success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherVocabularyRouteImport } from './routes/teacher.vocabulary'
import { Route as TeacherShadowingRouteImport } from './routes/teacher.shadowing'
import { Route as TeacherSettingsRouteImport } from './routes/teacher.settings'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherQuestionBankRouteImport } from './routes/teacher.question-bank'
import { Route as TeacherProgressRouteImport } from './routes/teacher.progress'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherListeningRouteImport } from './routes/teacher.listening'
import { Route as TeacherLessonsRouteImport } from './routes/teacher.lessons'
import { Route as TeacherJlptBankRouteImport } from './routes/teacher.jlpt-bank'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherGrammarRouteImport } from './routes/teacher.grammar'
import { Route as TeacherFlashcardsRouteImport } from './routes/teacher.flashcards'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherDataBankRouteImport } from './routes/teacher.data-bank'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as StudentVocabularyRouteImport } from './routes/student.vocabulary'
import { Route as StudentShadowingRouteImport } from './routes/student.shadowing'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentListeningRouteImport } from './routes/student.listening'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as StudentJlptRouteImport } from './routes/student.jlpt'
import { Route as StudentGrammarRouteImport } from './routes/student.grammar'
import { Route as StudentFlashcardsRouteImport } from './routes/student.flashcards'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentAiSenseiRouteImport } from './routes/student.ai-sensei'
import { Route as AdminVocabularyLibraryRouteImport } from './routes/admin.vocabulary-library'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminShadowingLibraryRouteImport } from './routes/admin.shadowing-library'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReadingLibraryRouteImport } from './routes/admin.reading-library'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminListeningLibraryRouteImport } from './routes/admin.listening-library'
import { Route as AdminGrammarApprovalRouteImport } from './routes/admin.grammar-approval'
import { Route as AdminGrammarRouteImport } from './routes/admin.grammar'
import { Route as AdminFlashcardLibraryRouteImport } from './routes/admin.flashcard-library'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminContentApprovalRouteImport } from './routes/admin.content-approval'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiGeneratorRouteImport } from './routes/admin.ai-generator'
import { Route as TeacherVocabularyLessonIdRouteImport } from './routes/teacher.vocabulary.$lessonId'
import { Route as TeacherLessonsCreateRouteImport } from './routes/teacher.lessons.create'
import { Route as TeacherHomeworkCreateRouteImport } from './routes/teacher.homework.create'
import { Route as TeacherExamsCreateRouteImport } from './routes/teacher.exams.create'
import { Route as TeacherClassesCreateRouteImport } from './routes/teacher.classes.create'
import { Route as TeacherClassesClassIdRouteImport } from './routes/teacher.classes.$classId'
import { Route as StudentVocabularyLessonIdRouteImport } from './routes/student.vocabulary.$lessonId'
import { Route as StudentGrammarIndexRouteImport } from './routes/student.grammar._index'
import { Route as StudentGrammarGrammarIdRouteImport } from './routes/student.grammar.$grammarId'
import { Route as TeacherClassesClassIdStudentsRouteImport } from './routes/teacher.classes.$classId.students'
import { Route as TeacherClassesClassIdProgressRouteImport } from './routes/teacher.classes.$classId.progress'
import { Route as TeacherClassesClassIdLessonsRouteImport } from './routes/teacher.classes.$classId.lessons'
import { Route as TeacherClassesClassIdHomeworkRouteImport } from './routes/teacher.classes.$classId.homework'
import { Route as TeacherClassesClassIdExamsRouteImport } from './routes/teacher.classes.$classId.exams'
import { Route as StudentGrammarGrammarIdStructureIdRouteImport } from './routes/student.grammar.$grammarId.$structureId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPendingRoute = TeacherPendingRouteImport.update({
  id: '/teacher-pending',
  path: '/teacher-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSuccessRoute = ResetSuccessRouteImport.update({
  id: '/reset-success',
  path: '/reset-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyRoute = TeacherVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherShadowingRoute = TeacherShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSettingsRoute = TeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuestionBankRoute = TeacherQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProgressRoute = TeacherProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherListeningRoute = TeacherListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLessonsRoute = TeacherLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherJlptBankRoute = TeacherJlptBankRouteImport.update({
  id: '/jlpt-bank',
  path: '/jlpt-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGrammarRoute = TeacherGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFlashcardsRoute = TeacherFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDataBankRoute = TeacherDataBankRouteImport.update({
  id: '/data-bank',
  path: '/data-bank',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVocabularyRoute = StudentVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => StudentRoute,
} as any)
const StudentShadowingRoute = StudentShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentJlptRoute = StudentJlptRouteImport.update({
  id: '/jlpt',
  path: '/jlpt',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGrammarRoute = StudentGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlashcardsRoute = StudentFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiSenseiRoute = StudentAiSenseiRouteImport.update({
  id: '/ai-sensei',
  path: '/ai-sensei',
  getParentRoute: () => StudentRoute,
} as any)
const AdminVocabularyLibraryRoute = AdminVocabularyLibraryRouteImport.update({
  id: '/vocabulary-library',
  path: '/vocabulary-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShadowingLibraryRoute = AdminShadowingLibraryRouteImport.update({
  id: '/shadowing-library',
  path: '/shadowing-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadingLibraryRoute = AdminReadingLibraryRouteImport.update({
  id: '/reading-library',
  path: '/reading-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListeningLibraryRoute = AdminListeningLibraryRouteImport.update({
  id: '/listening-library',
  path: '/listening-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrammarApprovalRoute = AdminGrammarApprovalRouteImport.update({
  id: '/grammar-approval',
  path: '/grammar-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrammarRoute = AdminGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlashcardLibraryRoute = AdminFlashcardLibraryRouteImport.update({
  id: '/flashcard-library',
  path: '/flashcard-library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentApprovalRoute = AdminContentApprovalRouteImport.update({
  id: '/content-approval',
  path: '/content-approval',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiGeneratorRoute = AdminAiGeneratorRouteImport.update({
  id: '/ai-generator',
  path: '/ai-generator',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherVocabularyLessonIdRoute =
  TeacherVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => TeacherVocabularyRoute,
  } as any)
const TeacherLessonsCreateRoute = TeacherLessonsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherLessonsRoute,
} as any)
const TeacherHomeworkCreateRoute = TeacherHomeworkCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherHomeworkRoute,
} as any)
const TeacherExamsCreateRoute = TeacherExamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherExamsRoute,
} as any)
const TeacherClassesCreateRoute = TeacherClassesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeacherClassesRoute,
} as any)
const TeacherClassesClassIdRoute = TeacherClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => TeacherClassesRoute,
} as any)
const StudentVocabularyLessonIdRoute =
  StudentVocabularyLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => StudentVocabularyRoute,
  } as any)
const StudentGrammarIndexRoute = StudentGrammarIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const StudentGrammarGrammarIdRoute = StudentGrammarGrammarIdRouteImport.update({
  id: '/$grammarId',
  path: '/$grammarId',
  getParentRoute: () => StudentGrammarRoute,
} as any)
const TeacherClassesClassIdStudentsRoute =
  TeacherClassesClassIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdProgressRoute =
  TeacherClassesClassIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdLessonsRoute =
  TeacherClassesClassIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdHomeworkRoute =
  TeacherClassesClassIdHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const TeacherClassesClassIdExamsRoute =
  TeacherClassesClassIdExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => TeacherClassesClassIdRoute,
  } as any)
const StudentGrammarGrammarIdStructureIdRoute =
  StudentGrammarGrammarIdStructureIdRouteImport.update({
    id: '/$structureId',
    path: '/$structureId',
    getParentRoute: () => StudentGrammarGrammarIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/flashcard-library': typeof AdminFlashcardLibraryRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/listening-library': typeof AdminListeningLibraryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reading-library': typeof AdminReadingLibraryRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shadowing-library': typeof AdminShadowingLibraryRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary-library': typeof AdminVocabularyLibraryRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/flashcard-library': typeof AdminFlashcardLibraryRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/listening-library': typeof AdminListeningLibraryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reading-library': typeof AdminReadingLibraryRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shadowing-library': typeof AdminShadowingLibraryRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary-library': typeof AdminVocabularyLibraryRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-success': typeof ResetSuccessRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/teacher-pending': typeof TeacherPendingRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content-approval': typeof AdminContentApprovalRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/flashcard-library': typeof AdminFlashcardLibraryRoute
  '/admin/grammar': typeof AdminGrammarRoute
  '/admin/grammar-approval': typeof AdminGrammarApprovalRoute
  '/admin/listening-library': typeof AdminListeningLibraryRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reading-library': typeof AdminReadingLibraryRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shadowing-library': typeof AdminShadowingLibraryRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary-library': typeof AdminVocabularyLibraryRoute
  '/student/ai-sensei': typeof StudentAiSenseiRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/flashcards': typeof StudentFlashcardsRoute
  '/student/grammar': typeof StudentGrammarRouteWithChildren
  '/student/jlpt': typeof StudentJlptRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/student/listening': typeof StudentListeningRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/shadowing': typeof StudentShadowingRoute
  '/student/vocabulary': typeof StudentVocabularyRouteWithChildren
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/data-bank': typeof TeacherDataBankRoute
  '/teacher/exams': typeof TeacherExamsRouteWithChildren
  '/teacher/flashcards': typeof TeacherFlashcardsRoute
  '/teacher/grammar': typeof TeacherGrammarRoute
  '/teacher/homework': typeof TeacherHomeworkRouteWithChildren
  '/teacher/jlpt-bank': typeof TeacherJlptBankRoute
  '/teacher/lessons': typeof TeacherLessonsRouteWithChildren
  '/teacher/listening': typeof TeacherListeningRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/teacher/question-bank': typeof TeacherQuestionBankRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/settings': typeof TeacherSettingsRoute
  '/teacher/shadowing': typeof TeacherShadowingRoute
  '/teacher/vocabulary': typeof TeacherVocabularyRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/grammar/$grammarId': typeof StudentGrammarGrammarIdRouteWithChildren
  '/student/grammar/_index': typeof StudentGrammarIndexRoute
  '/student/vocabulary/$lessonId': typeof StudentVocabularyLessonIdRoute
  '/teacher/classes/$classId': typeof TeacherClassesClassIdRouteWithChildren
  '/teacher/classes/create': typeof TeacherClassesCreateRoute
  '/teacher/exams/create': typeof TeacherExamsCreateRoute
  '/teacher/homework/create': typeof TeacherHomeworkCreateRoute
  '/teacher/lessons/create': typeof TeacherLessonsCreateRoute
  '/teacher/vocabulary/$lessonId': typeof TeacherVocabularyLessonIdRoute
  '/student/grammar/$grammarId/$structureId': typeof StudentGrammarGrammarIdStructureIdRoute
  '/teacher/classes/$classId/exams': typeof TeacherClassesClassIdExamsRoute
  '/teacher/classes/$classId/homework': typeof TeacherClassesClassIdHomeworkRoute
  '/teacher/classes/$classId/lessons': typeof TeacherClassesClassIdLessonsRoute
  '/teacher/classes/$classId/progress': typeof TeacherClassesClassIdProgressRoute
  '/teacher/classes/$classId/students': typeof TeacherClassesClassIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/flashcard-library'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/listening-library'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reading-library'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shadowing-library'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/vocabulary-library'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/flashcard-library'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/listening-library'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reading-library'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shadowing-library'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/vocabulary-library'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/grammar/$grammarId'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/reset-success'
    | '/student'
    | '/teacher'
    | '/teacher-pending'
    | '/verify-otp'
    | '/admin/ai-generator'
    | '/admin/analytics'
    | '/admin/content-approval'
    | '/admin/exams'
    | '/admin/flashcard-library'
    | '/admin/grammar'
    | '/admin/grammar-approval'
    | '/admin/listening-library'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reading-library'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shadowing-library'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/admin/vocabulary-library'
    | '/student/ai-sensei'
    | '/student/exams'
    | '/student/flashcards'
    | '/student/grammar'
    | '/student/jlpt'
    | '/student/leaderboard'
    | '/student/listening'
    | '/student/notifications'
    | '/student/profile'
    | '/student/progress'
    | '/student/shadowing'
    | '/student/vocabulary'
    | '/teacher/classes'
    | '/teacher/data-bank'
    | '/teacher/exams'
    | '/teacher/flashcards'
    | '/teacher/grammar'
    | '/teacher/homework'
    | '/teacher/jlpt-bank'
    | '/teacher/lessons'
    | '/teacher/listening'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/progress'
    | '/teacher/question-bank'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/shadowing'
    | '/teacher/vocabulary'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/grammar/$grammarId'
    | '/student/grammar/_index'
    | '/student/vocabulary/$lessonId'
    | '/teacher/classes/$classId'
    | '/teacher/classes/create'
    | '/teacher/exams/create'
    | '/teacher/homework/create'
    | '/teacher/lessons/create'
    | '/teacher/vocabulary/$lessonId'
    | '/student/grammar/$grammarId/$structureId'
    | '/teacher/classes/$classId/exams'
    | '/teacher/classes/$classId/homework'
    | '/teacher/classes/$classId/lessons'
    | '/teacher/classes/$classId/progress'
    | '/teacher/classes/$classId/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetSuccessRoute: typeof ResetSuccessRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TeacherPendingRoute: typeof TeacherPendingRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-pending': {
      id: '/teacher-pending'
      path: '/teacher-pending'
      fullPath: '/teacher-pending'
      preLoaderRoute: typeof TeacherPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-success': {
      id: '/reset-success'
      path: '/reset-success'
      fullPath: '/reset-success'
      preLoaderRoute: typeof ResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary': {
      id: '/teacher/vocabulary'
      path: '/vocabulary'
      fullPath: '/teacher/vocabulary'
      preLoaderRoute: typeof TeacherVocabularyRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/shadowing': {
      id: '/teacher/shadowing'
      path: '/shadowing'
      fullPath: '/teacher/shadowing'
      preLoaderRoute: typeof TeacherShadowingRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/settings': {
      id: '/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof TeacherSettingsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/question-bank': {
      id: '/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/teacher/question-bank'
      preLoaderRoute: typeof TeacherQuestionBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/progress': {
      id: '/teacher/progress'
      path: '/progress'
      fullPath: '/teacher/progress'
      preLoaderRoute: typeof TeacherProgressRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/listening': {
      id: '/teacher/listening'
      path: '/listening'
      fullPath: '/teacher/listening'
      preLoaderRoute: typeof TeacherListeningRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/lessons': {
      id: '/teacher/lessons'
      path: '/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof TeacherLessonsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/jlpt-bank': {
      id: '/teacher/jlpt-bank'
      path: '/jlpt-bank'
      fullPath: '/teacher/jlpt-bank'
      preLoaderRoute: typeof TeacherJlptBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grammar': {
      id: '/teacher/grammar'
      path: '/grammar'
      fullPath: '/teacher/grammar'
      preLoaderRoute: typeof TeacherGrammarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/flashcards': {
      id: '/teacher/flashcards'
      path: '/flashcards'
      fullPath: '/teacher/flashcards'
      preLoaderRoute: typeof TeacherFlashcardsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/data-bank': {
      id: '/teacher/data-bank'
      path: '/data-bank'
      fullPath: '/teacher/data-bank'
      preLoaderRoute: typeof TeacherDataBankRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/vocabulary': {
      id: '/student/vocabulary'
      path: '/vocabulary'
      fullPath: '/student/vocabulary'
      preLoaderRoute: typeof StudentVocabularyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/shadowing': {
      id: '/student/shadowing'
      path: '/shadowing'
      fullPath: '/student/shadowing'
      preLoaderRoute: typeof StudentShadowingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/jlpt': {
      id: '/student/jlpt'
      path: '/jlpt'
      fullPath: '/student/jlpt'
      preLoaderRoute: typeof StudentJlptRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grammar': {
      id: '/student/grammar'
      path: '/grammar'
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flashcards': {
      id: '/student/flashcards'
      path: '/flashcards'
      fullPath: '/student/flashcards'
      preLoaderRoute: typeof StudentFlashcardsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-sensei': {
      id: '/student/ai-sensei'
      path: '/ai-sensei'
      fullPath: '/student/ai-sensei'
      preLoaderRoute: typeof StudentAiSenseiRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/vocabulary-library': {
      id: '/admin/vocabulary-library'
      path: '/vocabulary-library'
      fullPath: '/admin/vocabulary-library'
      preLoaderRoute: typeof AdminVocabularyLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shadowing-library': {
      id: '/admin/shadowing-library'
      path: '/shadowing-library'
      fullPath: '/admin/shadowing-library'
      preLoaderRoute: typeof AdminShadowingLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reading-library': {
      id: '/admin/reading-library'
      path: '/reading-library'
      fullPath: '/admin/reading-library'
      preLoaderRoute: typeof AdminReadingLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listening-library': {
      id: '/admin/listening-library'
      path: '/listening-library'
      fullPath: '/admin/listening-library'
      preLoaderRoute: typeof AdminListeningLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grammar-approval': {
      id: '/admin/grammar-approval'
      path: '/grammar-approval'
      fullPath: '/admin/grammar-approval'
      preLoaderRoute: typeof AdminGrammarApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grammar': {
      id: '/admin/grammar'
      path: '/grammar'
      fullPath: '/admin/grammar'
      preLoaderRoute: typeof AdminGrammarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flashcard-library': {
      id: '/admin/flashcard-library'
      path: '/flashcard-library'
      fullPath: '/admin/flashcard-library'
      preLoaderRoute: typeof AdminFlashcardLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-approval': {
      id: '/admin/content-approval'
      path: '/content-approval'
      fullPath: '/admin/content-approval'
      preLoaderRoute: typeof AdminContentApprovalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-generator': {
      id: '/admin/ai-generator'
      path: '/ai-generator'
      fullPath: '/admin/ai-generator'
      preLoaderRoute: typeof AdminAiGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/vocabulary/$lessonId': {
      id: '/teacher/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/teacher/vocabulary/$lessonId'
      preLoaderRoute: typeof TeacherVocabularyLessonIdRouteImport
      parentRoute: typeof TeacherVocabularyRoute
    }
    '/teacher/lessons/create': {
      id: '/teacher/lessons/create'
      path: '/create'
      fullPath: '/teacher/lessons/create'
      preLoaderRoute: typeof TeacherLessonsCreateRouteImport
      parentRoute: typeof TeacherLessonsRoute
    }
    '/teacher/homework/create': {
      id: '/teacher/homework/create'
      path: '/create'
      fullPath: '/teacher/homework/create'
      preLoaderRoute: typeof TeacherHomeworkCreateRouteImport
      parentRoute: typeof TeacherHomeworkRoute
    }
    '/teacher/exams/create': {
      id: '/teacher/exams/create'
      path: '/create'
      fullPath: '/teacher/exams/create'
      preLoaderRoute: typeof TeacherExamsCreateRouteImport
      parentRoute: typeof TeacherExamsRoute
    }
    '/teacher/classes/create': {
      id: '/teacher/classes/create'
      path: '/create'
      fullPath: '/teacher/classes/create'
      preLoaderRoute: typeof TeacherClassesCreateRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
    '/teacher/classes/$classId': {
      id: '/teacher/classes/$classId'
      path: '/$classId'
      fullPath: '/teacher/classes/$classId'
      preLoaderRoute: typeof TeacherClassesClassIdRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
    '/student/vocabulary/$lessonId': {
      id: '/student/vocabulary/$lessonId'
      path: '/$lessonId'
      fullPath: '/student/vocabulary/$lessonId'
      preLoaderRoute: typeof StudentVocabularyLessonIdRouteImport
      parentRoute: typeof StudentVocabularyRoute
    }
    '/student/grammar/_index': {
      id: '/student/grammar/_index'
      path: ''
      fullPath: '/student/grammar'
      preLoaderRoute: typeof StudentGrammarIndexRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/student/grammar/$grammarId': {
      id: '/student/grammar/$grammarId'
      path: '/$grammarId'
      fullPath: '/student/grammar/$grammarId'
      preLoaderRoute: typeof StudentGrammarGrammarIdRouteImport
      parentRoute: typeof StudentGrammarRoute
    }
    '/teacher/classes/$classId/students': {
      id: '/teacher/classes/$classId/students'
      path: '/students'
      fullPath: '/teacher/classes/$classId/students'
      preLoaderRoute: typeof TeacherClassesClassIdStudentsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/progress': {
      id: '/teacher/classes/$classId/progress'
      path: '/progress'
      fullPath: '/teacher/classes/$classId/progress'
      preLoaderRoute: typeof TeacherClassesClassIdProgressRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/lessons': {
      id: '/teacher/classes/$classId/lessons'
      path: '/lessons'
      fullPath: '/teacher/classes/$classId/lessons'
      preLoaderRoute: typeof TeacherClassesClassIdLessonsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/homework': {
      id: '/teacher/classes/$classId/homework'
      path: '/homework'
      fullPath: '/teacher/classes/$classId/homework'
      preLoaderRoute: typeof TeacherClassesClassIdHomeworkRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/teacher/classes/$classId/exams': {
      id: '/teacher/classes/$classId/exams'
      path: '/exams'
      fullPath: '/teacher/classes/$classId/exams'
      preLoaderRoute: typeof TeacherClassesClassIdExamsRouteImport
      parentRoute: typeof TeacherClassesClassIdRoute
    }
    '/student/grammar/$grammarId/$structureId': {
      id: '/student/grammar/$grammarId/$structureId'
      path: '/$structureId'
      fullPath: '/student/grammar/$grammarId/$structureId'
      preLoaderRoute: typeof StudentGrammarGrammarIdStructureIdRouteImport
      parentRoute: typeof StudentGrammarGrammarIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiGeneratorRoute: typeof AdminAiGeneratorRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentApprovalRoute: typeof AdminContentApprovalRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFlashcardLibraryRoute: typeof AdminFlashcardLibraryRoute
  AdminGrammarRoute: typeof AdminGrammarRoute
  AdminGrammarApprovalRoute: typeof AdminGrammarApprovalRoute
  AdminListeningLibraryRoute: typeof AdminListeningLibraryRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReadingLibraryRoute: typeof AdminReadingLibraryRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShadowingLibraryRoute: typeof AdminShadowingLibraryRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVocabularyLibraryRoute: typeof AdminVocabularyLibraryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiGeneratorRoute: AdminAiGeneratorRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentApprovalRoute: AdminContentApprovalRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFlashcardLibraryRoute: AdminFlashcardLibraryRoute,
  AdminGrammarRoute: AdminGrammarRoute,
  AdminGrammarApprovalRoute: AdminGrammarApprovalRoute,
  AdminListeningLibraryRoute: AdminListeningLibraryRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReadingLibraryRoute: AdminReadingLibraryRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShadowingLibraryRoute: AdminShadowingLibraryRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVocabularyLibraryRoute: AdminVocabularyLibraryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentGrammarGrammarIdRouteChildren {
  StudentGrammarGrammarIdStructureIdRoute: typeof StudentGrammarGrammarIdStructureIdRoute
}

const StudentGrammarGrammarIdRouteChildren: StudentGrammarGrammarIdRouteChildren =
  {
    StudentGrammarGrammarIdStructureIdRoute:
      StudentGrammarGrammarIdStructureIdRoute,
  }

const StudentGrammarGrammarIdRouteWithChildren =
  StudentGrammarGrammarIdRoute._addFileChildren(
    StudentGrammarGrammarIdRouteChildren,
  )

interface StudentGrammarRouteChildren {
  StudentGrammarGrammarIdRoute: typeof StudentGrammarGrammarIdRouteWithChildren
  StudentGrammarIndexRoute: typeof StudentGrammarIndexRoute
}

const StudentGrammarRouteChildren: StudentGrammarRouteChildren = {
  StudentGrammarGrammarIdRoute: StudentGrammarGrammarIdRouteWithChildren,
  StudentGrammarIndexRoute: StudentGrammarIndexRoute,
}

const StudentGrammarRouteWithChildren = StudentGrammarRoute._addFileChildren(
  StudentGrammarRouteChildren,
)

interface StudentVocabularyRouteChildren {
  StudentVocabularyLessonIdRoute: typeof StudentVocabularyLessonIdRoute
}

const StudentVocabularyRouteChildren: StudentVocabularyRouteChildren = {
  StudentVocabularyLessonIdRoute: StudentVocabularyLessonIdRoute,
}

const StudentVocabularyRouteWithChildren =
  StudentVocabularyRoute._addFileChildren(StudentVocabularyRouteChildren)

interface StudentRouteChildren {
  StudentAiSenseiRoute: typeof StudentAiSenseiRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentFlashcardsRoute: typeof StudentFlashcardsRoute
  StudentGrammarRoute: typeof StudentGrammarRouteWithChildren
  StudentJlptRoute: typeof StudentJlptRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  StudentListeningRoute: typeof StudentListeningRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentShadowingRoute: typeof StudentShadowingRoute
  StudentVocabularyRoute: typeof StudentVocabularyRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiSenseiRoute: StudentAiSenseiRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentFlashcardsRoute: StudentFlashcardsRoute,
  StudentGrammarRoute: StudentGrammarRouteWithChildren,
  StudentJlptRoute: StudentJlptRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  StudentListeningRoute: StudentListeningRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentShadowingRoute: StudentShadowingRoute,
  StudentVocabularyRoute: StudentVocabularyRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherClassesClassIdRouteChildren {
  TeacherClassesClassIdExamsRoute: typeof TeacherClassesClassIdExamsRoute
  TeacherClassesClassIdHomeworkRoute: typeof TeacherClassesClassIdHomeworkRoute
  TeacherClassesClassIdLessonsRoute: typeof TeacherClassesClassIdLessonsRoute
  TeacherClassesClassIdProgressRoute: typeof TeacherClassesClassIdProgressRoute
  TeacherClassesClassIdStudentsRoute: typeof TeacherClassesClassIdStudentsRoute
}

const TeacherClassesClassIdRouteChildren: TeacherClassesClassIdRouteChildren = {
  TeacherClassesClassIdExamsRoute: TeacherClassesClassIdExamsRoute,
  TeacherClassesClassIdHomeworkRoute: TeacherClassesClassIdHomeworkRoute,
  TeacherClassesClassIdLessonsRoute: TeacherClassesClassIdLessonsRoute,
  TeacherClassesClassIdProgressRoute: TeacherClassesClassIdProgressRoute,
  TeacherClassesClassIdStudentsRoute: TeacherClassesClassIdStudentsRoute,
}

const TeacherClassesClassIdRouteWithChildren =
  TeacherClassesClassIdRoute._addFileChildren(
    TeacherClassesClassIdRouteChildren,
  )

interface TeacherClassesRouteChildren {
  TeacherClassesClassIdRoute: typeof TeacherClassesClassIdRouteWithChildren
  TeacherClassesCreateRoute: typeof TeacherClassesCreateRoute
}

const TeacherClassesRouteChildren: TeacherClassesRouteChildren = {
  TeacherClassesClassIdRoute: TeacherClassesClassIdRouteWithChildren,
  TeacherClassesCreateRoute: TeacherClassesCreateRoute,
}

const TeacherClassesRouteWithChildren = TeacherClassesRoute._addFileChildren(
  TeacherClassesRouteChildren,
)

interface TeacherExamsRouteChildren {
  TeacherExamsCreateRoute: typeof TeacherExamsCreateRoute
}

const TeacherExamsRouteChildren: TeacherExamsRouteChildren = {
  TeacherExamsCreateRoute: TeacherExamsCreateRoute,
}

const TeacherExamsRouteWithChildren = TeacherExamsRoute._addFileChildren(
  TeacherExamsRouteChildren,
)

interface TeacherHomeworkRouteChildren {
  TeacherHomeworkCreateRoute: typeof TeacherHomeworkCreateRoute
}

const TeacherHomeworkRouteChildren: TeacherHomeworkRouteChildren = {
  TeacherHomeworkCreateRoute: TeacherHomeworkCreateRoute,
}

const TeacherHomeworkRouteWithChildren = TeacherHomeworkRoute._addFileChildren(
  TeacherHomeworkRouteChildren,
)

interface TeacherLessonsRouteChildren {
  TeacherLessonsCreateRoute: typeof TeacherLessonsCreateRoute
}

const TeacherLessonsRouteChildren: TeacherLessonsRouteChildren = {
  TeacherLessonsCreateRoute: TeacherLessonsCreateRoute,
}

const TeacherLessonsRouteWithChildren = TeacherLessonsRoute._addFileChildren(
  TeacherLessonsRouteChildren,
)

interface TeacherVocabularyRouteChildren {
  TeacherVocabularyLessonIdRoute: typeof TeacherVocabularyLessonIdRoute
}

const TeacherVocabularyRouteChildren: TeacherVocabularyRouteChildren = {
  TeacherVocabularyLessonIdRoute: TeacherVocabularyLessonIdRoute,
}

const TeacherVocabularyRouteWithChildren =
  TeacherVocabularyRoute._addFileChildren(TeacherVocabularyRouteChildren)

interface TeacherRouteChildren {
  TeacherClassesRoute: typeof TeacherClassesRouteWithChildren
  TeacherDataBankRoute: typeof TeacherDataBankRoute
  TeacherExamsRoute: typeof TeacherExamsRouteWithChildren
  TeacherFlashcardsRoute: typeof TeacherFlashcardsRoute
  TeacherGrammarRoute: typeof TeacherGrammarRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRouteWithChildren
  TeacherJlptBankRoute: typeof TeacherJlptBankRoute
  TeacherLessonsRoute: typeof TeacherLessonsRouteWithChildren
  TeacherListeningRoute: typeof TeacherListeningRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherProgressRoute: typeof TeacherProgressRoute
  TeacherQuestionBankRoute: typeof TeacherQuestionBankRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSettingsRoute: typeof TeacherSettingsRoute
  TeacherShadowingRoute: typeof TeacherShadowingRoute
  TeacherVocabularyRoute: typeof TeacherVocabularyRouteWithChildren
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherClassesRoute: TeacherClassesRouteWithChildren,
  TeacherDataBankRoute: TeacherDataBankRoute,
  TeacherExamsRoute: TeacherExamsRouteWithChildren,
  TeacherFlashcardsRoute: TeacherFlashcardsRoute,
  TeacherGrammarRoute: TeacherGrammarRoute,
  TeacherHomeworkRoute: TeacherHomeworkRouteWithChildren,
  TeacherJlptBankRoute: TeacherJlptBankRoute,
  TeacherLessonsRoute: TeacherLessonsRouteWithChildren,
  TeacherListeningRoute: TeacherListeningRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherProgressRoute: TeacherProgressRoute,
  TeacherQuestionBankRoute: TeacherQuestionBankRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSettingsRoute: TeacherSettingsRoute,
  TeacherShadowingRoute: TeacherShadowingRoute,
  TeacherVocabularyRoute: TeacherVocabularyRouteWithChildren,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetSuccessRoute: ResetSuccessRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TeacherPendingRoute: TeacherPendingRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
