-- Add columns to hiragana_characters and katakana_characters tables if they do not exist
ALTER TABLE hiragana_characters ADD COLUMN IF NOT EXISTS meaning VARCHAR(255);
ALTER TABLE hiragana_characters ADD COLUMN IF NOT EXISTS example_word VARCHAR(255);
ALTER TABLE hiragana_characters ADD COLUMN IF NOT EXISTS example_meaning VARCHAR(255);

ALTER TABLE katakana_characters ADD COLUMN IF NOT EXISTS meaning VARCHAR(255);
ALTER TABLE katakana_characters ADD COLUMN IF NOT EXISTS example_word VARCHAR(255);
ALTER TABLE katakana_characters ADD COLUMN IF NOT EXISTS example_meaning VARCHAR(255);

UPDATE hiragana_characters SET meaning = 'vowel a', example_word = 'あめ', example_meaning = 'rain' WHERE character = 'あ';
UPDATE hiragana_characters SET meaning = 'vowel i', example_word = 'いぬ', example_meaning = 'dog' WHERE character = 'い';
UPDATE hiragana_characters SET meaning = 'vowel u', example_word = 'うみ', example_meaning = 'sea' WHERE character = 'う';
UPDATE hiragana_characters SET meaning = 'vowel e', example_word = 'えき', example_meaning = 'station' WHERE character = 'え';
UPDATE hiragana_characters SET meaning = 'vowel o', example_word = 'おとこ', example_meaning = 'man' WHERE character = 'お';
UPDATE hiragana_characters SET meaning = 'ka', example_word = 'かさ', example_meaning = 'umbrella' WHERE character = 'か';
UPDATE hiragana_characters SET meaning = 'ki', example_word = 'きもの', example_meaning = 'kimono' WHERE character = 'き';
UPDATE hiragana_characters SET meaning = 'ku', example_word = 'くつ', example_meaning = 'shoes' WHERE character = 'く';
UPDATE hiragana_characters SET meaning = 'ke', example_word = 'けさ', example_meaning = 'this morning' WHERE character = 'け';
UPDATE hiragana_characters SET meaning = 'ko', example_word = 'こえ', example_meaning = 'voice' WHERE character = 'こ';
UPDATE hiragana_characters SET meaning = 'sa', example_word = 'さくら', example_meaning = 'cherry blossom' WHERE character = 'さ';
UPDATE hiragana_characters SET meaning = 'shi', example_word = 'しお', example_meaning = 'salt' WHERE character = 'し';
UPDATE hiragana_characters SET meaning = 'su', example_word = 'すし', example_meaning = 'sushi' WHERE character = 'す';
UPDATE hiragana_characters SET meaning = 'se', example_word = 'せかい', example_meaning = 'world' WHERE character = 'せ';
UPDATE hiragana_characters SET meaning = 'so', example_word = 'そら', example_meaning = 'sky' WHERE character = 'そ';
UPDATE hiragana_characters SET meaning = 'ta', example_word = 'たまご', example_meaning = 'egg' WHERE character = 'た';
UPDATE hiragana_characters SET meaning = 'chi', example_word = 'ちず', example_meaning = 'map' WHERE character = 'ち';
UPDATE hiragana_characters SET meaning = 'tsu', example_word = 'つき', example_meaning = 'moon' WHERE character = 'つ';
UPDATE hiragana_characters SET meaning = 'te', example_word = 'てがみ', example_meaning = 'letter' WHERE character = 'て';
UPDATE hiragana_characters SET meaning = 'to', example_word = 'とり', example_meaning = 'bird' WHERE character = 'と';
UPDATE hiragana_characters SET meaning = 'na', example_word = 'なつ', example_meaning = 'summer' WHERE character = 'な';
UPDATE hiragana_characters SET meaning = 'ni', example_word = 'にほん', example_meaning = 'Japan' WHERE character = 'に';
UPDATE hiragana_characters SET meaning = 'nu', example_word = 'いぬ', example_meaning = 'dog' WHERE character = 'ぬ';
UPDATE hiragana_characters SET meaning = 'ne', example_word = 'ねこ', example_meaning = 'cat' WHERE character = 'ね';
UPDATE hiragana_characters SET meaning = 'no', example_word = 'のみず', example_meaning = 'drinking water' WHERE character = 'の';
UPDATE hiragana_characters SET meaning = 'ha', example_word = 'はな', example_meaning = 'flower' WHERE character = 'は';
UPDATE hiragana_characters SET meaning = 'hi', example_word = 'ひと', example_meaning = 'person' WHERE character = 'ひ';
UPDATE hiragana_characters SET meaning = 'fu', example_word = 'ふゆ', example_meaning = 'winter' WHERE character = 'ふ';
UPDATE hiragana_characters SET meaning = 'he', example_word = 'へや', example_meaning = 'room' WHERE character = 'へ';
UPDATE hiragana_characters SET meaning = 'ho', example_word = 'ほし', example_meaning = 'star' WHERE character = 'ほ';
UPDATE hiragana_characters SET meaning = 'ma', example_word = 'まち', example_meaning = 'town' WHERE character = 'ま';
UPDATE hiragana_characters SET meaning = 'mi', example_word = 'みみ', example_meaning = 'ear' WHERE character = 'み';
UPDATE hiragana_characters SET meaning = 'mu', example_word = 'むすめ', example_meaning = 'daughter' WHERE character = 'む';
UPDATE hiragana_characters SET meaning = 'me', example_word = 'め', example_meaning = 'eye' WHERE character = 'め';
UPDATE hiragana_characters SET meaning = 'mo', example_word = 'もり', example_meaning = 'forest' WHERE character = 'も';
UPDATE hiragana_characters SET meaning = 'ya', example_word = 'やま', example_meaning = 'mountain' WHERE character = 'や';
UPDATE hiragana_characters SET meaning = 'yu', example_word = 'ゆき', example_meaning = 'snow' WHERE character = 'ゆ';
UPDATE hiragana_characters SET meaning = 'yo', example_word = 'よる', example_meaning = 'night' WHERE character = 'よ';
UPDATE hiragana_characters SET meaning = 'ra', example_word = 'らいねん', example_meaning = 'next year' WHERE character = 'ら';
UPDATE hiragana_characters SET meaning = 'ri', example_word = 'りんご', example_meaning = 'apple' WHERE character = 'り';
UPDATE hiragana_characters SET meaning = 'ru', example_word = 'いる', example_meaning = 'to be (living)' WHERE character = 'る';
UPDATE hiragana_characters SET meaning = 're', example_word = 'れきし', example_meaning = 'history' WHERE character = 'れ';
UPDATE hiragana_characters SET meaning = 'ro', example_word = 'ろく', example_meaning = 'six' WHERE character = 'ろ';
UPDATE hiragana_characters SET meaning = 'wa', example_word = 'わたし', example_meaning = 'I/me' WHERE character = 'わ';
UPDATE hiragana_characters SET meaning = 'wo (particle)', example_word = 'みずをのむ', example_meaning = 'drink water' WHERE character = 'を';
UPDATE hiragana_characters SET meaning = 'n (consonant)', example_word = 'にほん', example_meaning = 'Japan' WHERE character = 'ん';
UPDATE hiragana_characters SET meaning = 'ga (voiced ka)', example_word = 'がっこう', example_meaning = 'school' WHERE character = 'が';
UPDATE hiragana_characters SET meaning = 'gi (voiced ki)', example_word = 'ぎんか', example_meaning = 'silver flower' WHERE character = 'ぎ';
UPDATE hiragana_characters SET meaning = 'gu (voiced ku)', example_word = 'ぐんかん', example_meaning = 'military officer' WHERE character = 'ぐ';
UPDATE hiragana_characters SET meaning = 'ge (voiced ke)', example_word = 'げんき', example_meaning = 'healthy' WHERE character = 'げ';
UPDATE hiragana_characters SET meaning = 'go (voiced ko)', example_word = 'ごみをすてる', example_meaning = 'throw away trash' WHERE character = 'ご';
UPDATE hiragana_characters SET meaning = 'za (voiced sa)', example_word = 'ざっし', example_meaning = 'magazine' WHERE character = 'ざ';
UPDATE hiragana_characters SET meaning = 'ji (voiced shi)', example_word = 'じしょ', example_meaning = 'dictionary' WHERE character = 'じ';
UPDATE hiragana_characters SET meaning = 'zu (voiced su)', example_word = 'ずっと', example_meaning = 'all the way' WHERE character = 'ず';
UPDATE hiragana_characters SET meaning = 'ze (voiced se)', example_word = 'ぜったい', example_meaning = 'absolute' WHERE character = 'ぜ';
UPDATE hiragana_characters SET meaning = 'zo (voiced so)', example_word = 'ぞくせい', example_meaning = '属性' WHERE character = 'ぞ';
UPDATE hiragana_characters SET meaning = 'da (voiced ta)', example_word = 'だいがく', example_meaning = 'university' WHERE character = 'だ';
UPDATE hiragana_characters SET meaning = 'di (voiced chi)', example_word = 'ぢん', example_meaning = '斤 (old unit)' WHERE character = 'ぢ';
UPDATE hiragana_characters SET meaning = 'du (voiced tsu)', example_word = 'つながる', example_meaning = 'to be connected' WHERE character = 'づ';
UPDATE hiragana_characters SET meaning = 'de (voiced te)', example_word = 'でかける', example_meaning = 'to go out' WHERE character = 'で';
UPDATE hiragana_characters SET meaning = 'do (voiced to)', example_word = 'どこ', example_meaning = 'where' WHERE character = 'ど';
UPDATE hiragana_characters SET meaning = 'ba (voiced ha)', example_word = 'ばす', example_meaning = 'bus' WHERE character = 'ば';
UPDATE hiragana_characters SET meaning = 'bi (voiced hi)', example_word = 'びょういん', example_meaning = 'hospital' WHERE character = 'び';
UPDATE hiragana_characters SET meaning = 'bu (voiced fu)', example_word = 'ぶちょう', example_meaning = 'department chief' WHERE character = 'ぶ';
UPDATE hiragana_characters SET meaning = 'be (voiced he)', example_word = 'べんきょう', example_meaning = 'study' WHERE character = 'べ';
UPDATE hiragana_characters SET meaning = 'bo (voiced ho)', example_word = 'ぼし', example_meaning = 'star (astronomy)' WHERE character = 'ぼ';
UPDATE hiragana_characters SET meaning = 'pa (semi-voiced ha)', example_word = 'ぱそこん', example_meaning = 'computer' WHERE character = 'ぱ';
UPDATE hiragana_characters SET meaning = 'pi (semi-voiced hi)', example_word = 'ぴあの', example_meaning = 'piano' WHERE character = 'ぴ';
UPDATE hiragana_characters SET meaning = 'pu (semi-voiced fu)', example_word = 'ぷり', example_meaning = 'plum (pickled)' WHERE character = 'ぷ';
UPDATE hiragana_characters SET meaning = 'pe (semi-voiced he)', example_word = 'ぺん', example_meaning = 'pen (writing)' WHERE character = 'ぺ';
UPDATE hiragana_characters SET meaning = 'po (semi-voiced ho)', example_word = 'ぽけっと', example_meaning = 'pocket' WHERE character = 'ぽ';
UPDATE hiragana_characters SET meaning = 'kya', example_word = 'きゃく', example_meaning = 'customer' WHERE character = 'きゃ';
UPDATE hiragana_characters SET meaning = 'kyu', example_word = 'きゅうり', example_meaning = 'cucumber' WHERE character = 'きゅ';
UPDATE hiragana_characters SET meaning = 'kyo', example_word = 'きょう', example_meaning = 'today' WHERE character = 'きょ';
UPDATE hiragana_characters SET meaning = 'sha', example_word = 'しゃしん', example_meaning = 'photo' WHERE character = 'しゃ';
UPDATE hiragana_characters SET meaning = 'shu', example_word = 'しゅくだい', example_meaning = 'homework' WHERE character = 'しゅ';
UPDATE hiragana_characters SET meaning = 'sho', example_word = 'しょうがくせい', example_meaning = 'elementary student' WHERE character = 'しょ';
UPDATE hiragana_characters SET meaning = 'cha', example_word = 'ちゃいろ', example_meaning = 'tea color' WHERE character = 'ちゃ';
UPDATE hiragana_characters SET meaning = 'chu', example_word = 'ちゅうがく', example_meaning = 'middle school' WHERE character = 'ちゅ';
UPDATE hiragana_characters SET meaning = 'cho', example_word = 'ちょうど', example_meaning = 'just right' WHERE character = 'ちょ';
UPDATE hiragana_characters SET meaning = 'nya', example_word = 'にゃんこ', example_meaning = 'kitty' WHERE character = 'にゃ';
UPDATE hiragana_characters SET meaning = 'nyu', example_word = 'にゅうがく', example_meaning = 'entering school' WHERE character = 'にゅ';
UPDATE hiragana_characters SET meaning = 'nyo', example_word = 'にょうほう', example_meaning = 'gypsum' WHERE character = 'にょ';
UPDATE hiragana_characters SET meaning = 'hya', example_word = 'ひゃく', example_meaning = 'hundred' WHERE character = 'ひゃ';
UPDATE hiragana_characters SET meaning = 'hyu', example_word = 'ひゅうえい', example_meaning = '休泳 (swim ban)' WHERE character = 'ひゅ';
UPDATE hiragana_characters SET meaning = 'hyo', example_word = 'ひょうたん', example_meaning = 'gourd' WHERE character = 'ひょ';
UPDATE hiragana_characters SET meaning = 'mya', example_word = 'みゃく', example_meaning = '脈 (pulse)' WHERE character = 'みゃ';
UPDATE hiragana_characters SET meaning = 'myu', example_word = 'みゅうちょう', example_meaning = '明治 (Meiji era)' WHERE character = 'みゅ';
UPDATE hiragana_characters SET meaning = 'myo', example_word = 'みょうにち', example_meaning = 'tomorrow' WHERE character = 'みょ';
UPDATE hiragana_characters SET meaning = 'rya', example_word = 'りゃくだん', example_meaning = 'logic' WHERE character = 'りゃ';
UPDATE hiragana_characters SET meaning = 'ryu', example_word = 'りゅうがく', example_meaning = 'studying abroad' WHERE character = 'りゅ';
UPDATE hiragana_characters SET meaning = 'ryo', example_word = 'りょうり', example_meaning = 'cooking' WHERE character = 'りょ';
UPDATE hiragana_characters SET meaning = 'gya', example_word = 'ぎゃく', example_meaning = 'evil' WHERE character = 'ぎゃ';
UPDATE hiragana_characters SET meaning = 'gyu', example_word = 'ぎゅうにゅう', example_meaning = 'milk' WHERE character = 'ぎゅ';
UPDATE hiragana_characters SET meaning = 'gyo', example_word = 'ぎょうぎ', example_meaning = 'manners' WHERE character = 'ぎょ';
UPDATE hiragana_characters SET meaning = 'ja', example_word = 'ジャケット', example_meaning = 'jacket' WHERE character = 'じゃ';
UPDATE hiragana_characters SET meaning = 'ju', example_word = 'じゅう', example_meaning = 'ten' WHERE character = 'じゅ';
UPDATE hiragana_characters SET meaning = 'jo', example_word = 'じょせい', example_meaning = 'woman' WHERE character = 'じょ';
UPDATE hiragana_characters SET meaning = 'bya', example_word = 'びゃくいん', example_meaning = 'hospital staff' WHERE character = 'びゃ';
UPDATE hiragana_characters SET meaning = 'byu', example_word = 'びゅういん', example_meaning = '美ugu' WHERE character = 'びゅ';
UPDATE hiragana_characters SET meaning = 'byo', example_word = 'びょういん', example_meaning = 'hospital' WHERE character = 'びょ';
UPDATE hiragana_characters SET meaning = 'pya', example_word = 'ぴゃん', example_meaning = 'meow' WHERE character = 'ぴゃ';
UPDATE hiragana_characters SET meaning = 'pyu', example_word = 'ぴゅう', example_meaning = 'whoosh' WHERE character = 'ぴゅ';
UPDATE hiragana_characters SET meaning = 'pyo', example_word = 'ぴょう', example_meaning = '坪 (area unit)' WHERE character = 'ぴょ';
UPDATE katakana_characters SET meaning = 'vowel a', example_word = 'アメリカ', example_meaning = 'America' WHERE character = 'ア';
UPDATE katakana_characters SET meaning = 'vowel i', example_word = 'イギリス', example_meaning = 'England' WHERE character = 'イ';
UPDATE katakana_characters SET meaning = 'vowel u', example_word = '宇宙', example_meaning = 'universe' WHERE character = 'ウ';
UPDATE katakana_characters SET meaning = 'vowel e', example_word = 'エレベーター', example_meaning = 'elevator' WHERE character = 'エ';
UPDATE katakana_characters SET meaning = 'vowel o', example_word = 'オレンジ', example_meaning = 'orange' WHERE character = 'オ';
UPDATE katakana_characters SET meaning = 'ka', example_word = 'カード', example_meaning = 'card' WHERE character = 'カ';
UPDATE katakana_characters SET meaning = 'ki', example_word = 'キス', example_meaning = 'kiss' WHERE character = 'キ';
UPDATE katakana_characters SET meaning = 'ku', example_word = 'クラス', example_meaning = 'class' WHERE character = 'ク';
UPDATE katakana_characters SET meaning = 'ke', example_word = 'ゲーム', example_meaning = 'game' WHERE character = 'ケ';
UPDATE katakana_characters SET meaning = 'ko', example_word = 'コーヒー', example_meaning = 'coffee' WHERE character = 'コ';
UPDATE katakana_characters SET meaning = 'sa', example_word = 'サービス', example_meaning = 'service' WHERE character = 'サ';
UPDATE katakana_characters SET meaning = 'shi', example_word = 'シャツ', example_meaning = 'shirt' WHERE character = 'シ';
UPDATE katakana_characters SET meaning = 'su', example_word = 'スター', example_meaning = 'star' WHERE character = 'ス';
UPDATE katakana_characters SET meaning = 'se', example_word = 'セーター', example_meaning = 'sweater' WHERE character = 'セ';
UPDATE katakana_characters SET meaning = 'so', example_word = 'ソファ', example_meaning = 'sofa' WHERE character = 'ソ';
UPDATE katakana_characters SET meaning = 'ta', example_word = 'テーブル', example_meaning = 'table' WHERE character = 'タ';
UPDATE katakana_characters SET meaning = 'chi', example_word = 'チーム', example_meaning = 'team' WHERE character = 'チ';
UPDATE katakana_characters SET meaning = 'tsu', example_word = 'ツインテール', example_meaning = 'twin tails' WHERE character = 'ツ';
UPDATE katakana_characters SET meaning = 'te', example_word = 'テレビ', example_meaning = 'television' WHERE character = 'テ';
UPDATE katakana_characters SET meaning = 'to', example_word = 'トピック', example_meaning = 'topic' WHERE character = 'ト';
UPDATE katakana_characters SET meaning = 'na', example_word = 'ナビ', example_meaning = 'navigation' WHERE character = 'ナ';
UPDATE katakana_characters SET meaning = 'ni', example_word = 'ニーズ', example_meaning = 'needs' WHERE character = 'ニ';
UPDATE katakana_characters SET meaning = 'nu', example_word = 'ヌードル', example_meaning = 'noodle' WHERE character = 'ヌ';
UPDATE katakana_characters SET meaning = 'ne', example_word = 'ネック', example_meaning = 'neck' WHERE character = 'ネ';
UPDATE katakana_characters SET meaning = 'no', example_word = 'ノート', example_meaning = 'notebook' WHERE character = 'ノ';
UPDATE katakana_characters SET meaning = 'ha', example_word = 'バッグ', example_meaning = 'bag' WHERE character = 'ハ';
UPDATE katakana_characters SET meaning = 'hi', example_word = 'ビデオ', example_meaning = 'video' WHERE character = 'ヒ';
UPDATE katakana_characters SET meaning = 'fu', example_word = 'ファミリー', example_meaning = 'family' WHERE character = 'フ';
UPDATE katakana_characters SET meaning = 'he', example_word = 'ヘア', example_meaning = 'hair' WHERE character = 'ヘ';
UPDATE katakana_characters SET meaning = 'ho', example_word = 'ホテル', example_meaning = 'hotel' WHERE character = 'ホ';
UPDATE katakana_characters SET meaning = 'ma', example_word = 'マスター', example_meaning = 'master' WHERE character = 'マ';
UPDATE katakana_characters SET meaning = 'mi', example_word = 'メール', example_meaning = 'email' WHERE character = 'ミ';
UPDATE katakana_characters SET meaning = 'mu', example_word = 'マンション', example_meaning = 'mansion/condo' WHERE character = 'ム';
UPDATE katakana_characters SET meaning = 'me', example_word = 'メニュー', example_meaning = 'menu' WHERE character = 'メ';
UPDATE katakana_characters SET meaning = 'mo', example_word = 'モデル', example_meaning = 'model' WHERE character = 'モ';
UPDATE katakana_characters SET meaning = 'ya', example_word = 'ヤング', example_meaning = 'young' WHERE character = 'ヤ';
UPDATE katakana_characters SET meaning = 'yu', example_word = 'ユーモア', example_meaning = 'humor' WHERE character = 'ユ';
UPDATE katakana_characters SET meaning = 'yo', example_word = 'ヨーロッパ', example_meaning = 'Europe' WHERE character = 'ヨ';
UPDATE katakana_characters SET meaning = 'ra', example_word = 'ラーメン', example_meaning = 'ramen' WHERE character = 'ラ';
UPDATE katakana_characters SET meaning = 'ri', example_word = 'リクエスト', example_meaning = 'request' WHERE character = 'リ';
UPDATE katakana_characters SET meaning = 'ru', example_word = 'ルール', example_meaning = 'rule' WHERE character = 'ル';
UPDATE katakana_characters SET meaning = 're', example_word = 'レポート', example_meaning = 'report' WHERE character = 'レ';
UPDATE katakana_characters SET meaning = 'ro', example_word = 'ロッカー', example_meaning = 'locker' WHERE character = 'ロ';
UPDATE katakana_characters SET meaning = 'wa', example_word = 'ワイン', example_meaning = 'wine' WHERE character = 'ワ';
UPDATE katakana_characters SET meaning = 'wo (archaic)', example_word = 'ヲタク', example_meaning = 'otaku' WHERE character = 'ヲ';
UPDATE katakana_characters SET meaning = 'n (consonant)', example_word = 'インターネット', example_meaning = 'internet' WHERE character = 'ン';
UPDATE katakana_characters SET meaning = 'ga (voiced ka)', example_word = 'ガス', example_meaning = 'gas' WHERE character = 'ガ';
UPDATE katakana_characters SET meaning = 'gi (voiced ki)', example_word = 'ギルド', example_meaning = 'guild' WHERE character = 'ギ';
UPDATE katakana_characters SET meaning = 'gu (voiced ku)', example_word = 'グレード', example_meaning = 'grade' WHERE character = 'グ';
UPDATE katakana_characters SET meaning = 'ge (voiced ke)', example_word = 'ゲート', example_meaning = 'gate' WHERE character = 'ゲ';
UPDATE katakana_characters SET meaning = 'go (voiced ko)', example_word = 'ゴール', example_meaning = 'goal' WHERE character = 'ゴ';
UPDATE katakana_characters SET meaning = 'za (voiced sa)', example_word = 'ザイン', example_meaning = 'design' WHERE character = 'ザ';
UPDATE katakana_characters SET meaning = 'ji (voiced shi)', example_word = 'ジャーナリスト', example_meaning = 'journalist' WHERE character = 'ジ';
UPDATE katakana_characters SET meaning = 'zu (voiced su)', example_word = 'ブルー', example_meaning = 'blue' WHERE character = 'ズ';
UPDATE katakana_characters SET meaning = 'ze (voiced se)', example_word = 'ゼロ', example_meaning = 'zero' WHERE character = 'ゼ';
UPDATE katakana_characters SET meaning = 'zo (voiced so)', example_word = 'ゾーン', example_meaning = 'zone' WHERE character = 'ゾ';
UPDATE katakana_characters SET meaning = 'da (voiced ta)', example_word = 'ダンス', example_meaning = 'dance' WHERE character = 'ダ';
UPDATE katakana_characters SET meaning = 'di (voiced chi)', example_word = 'ヂャラ', example_meaning = 'diva' WHERE character = 'ヂ';
UPDATE katakana_characters SET meaning = 'du (voiced tsu)', example_word = 'ヅル', example_meaning = 'Dru' WHERE character = 'ヅ';
UPDATE katakana_characters SET meaning = 'de (voiced te)', example_word = 'データ', example_meaning = 'data' WHERE character = 'デ';
UPDATE katakana_characters SET meaning = 'do (voiced to)', example_word = 'ドア', example_meaning = 'door' WHERE character = 'ド';
UPDATE katakana_characters SET meaning = 'ba (voiced ha)', example_word = 'ビジネス', example_meaning = 'business' WHERE character = 'バ';
UPDATE katakana_characters SET meaning = 'bi (voiced hi)', example_word = 'ビル', example_meaning = 'building' WHERE character = 'ビ';
UPDATE katakana_characters SET meaning = 'bu (voiced fu)', example_word = 'ブルー', example_meaning = 'blue' WHERE character = 'ブ';
UPDATE katakana_characters SET meaning = 'be (voiced he)', example_word = 'ベッド', example_meaning = 'bed' WHERE character = 'ベ';
UPDATE katakana_characters SET meaning = 'bo (voiced ho)', example_word = 'ボディ', example_meaning = 'body' WHERE character = 'ボ';
UPDATE katakana_characters SET meaning = 'pa (semi-voiced ha)', example_word = 'パーティ', example_meaning = 'party' WHERE character = 'パ';
UPDATE katakana_characters SET meaning = 'pi (semi-voiced hi)', example_word = 'ピンク', example_meaning = 'pink' WHERE character = 'ピ';
UPDATE katakana_characters SET meaning = 'pu (semi-voiced fu)', example_word = 'プール', example_meaning = 'pool' WHERE character = 'プ';
UPDATE katakana_characters SET meaning = 'pe (semi-voiced he)', example_word = 'ペン', example_meaning = 'pen' WHERE character = 'ペ';
UPDATE katakana_characters SET meaning = 'po (semi-voiced ho)', example_word = 'ポスト', example_meaning = 'post' WHERE character = 'ポ';
UPDATE katakana_characters SET meaning = 'kya', example_word = 'キャラクター', example_meaning = 'character' WHERE character = 'キャ';
UPDATE katakana_characters SET meaning = 'kyu', example_word = 'キューブ', example_meaning = 'cube' WHERE character = 'キュ';
UPDATE katakana_characters SET meaning = 'kyo', example_word = 'キャンセル', example_meaning = 'cancel' WHERE character = 'キョ';
UPDATE katakana_characters SET meaning = 'sha', example_word = 'シャープ', example_meaning = 'sharp' WHERE character = 'シャ';
UPDATE katakana_characters SET meaning = 'shu', example_word = 'シュガー', example_meaning = 'sugar' WHERE character = 'シュ';
UPDATE katakana_characters SET meaning = 'sho', example_word = 'ショップ', example_meaning = 'shop' WHERE character = 'ショ';
UPDATE katakana_characters SET meaning = 'cha', example_word = 'チャンネル', example_meaning = 'channel' WHERE character = 'チャ';
UPDATE katakana_characters SET meaning = 'chu', example_word = 'チューリップ', example_meaning = 'tulip' WHERE character = 'チュ';
UPDATE katakana_characters SET meaning = 'cho', example_word = 'チョコレート', example_meaning = 'chocolate' WHERE character = 'チョ';
UPDATE katakana_characters SET meaning = 'nya', example_word = 'ニュアンス', example_meaning = 'nuance' WHERE character = 'ニャ';
UPDATE katakana_characters SET meaning = 'nyu', example_word = 'ニュートン', example_meaning = 'Newton' WHERE character = 'ニュ';
UPDATE katakana_characters SET meaning = 'nyo', example_word = 'ニーズ', example_meaning = 'needs' WHERE character = 'ニョ';
UPDATE katakana_characters SET meaning = 'hya', example_word = 'ヒャッハー', example_meaning = 'yahoo' WHERE character = 'ヒャ';
UPDATE katakana_characters SET meaning = 'hyu', example_word = 'ヒューマニズム', example_meaning = 'humanism' WHERE character = 'ヒュ';
UPDATE katakana_characters SET meaning = 'hyo', example_word = 'ヒョウタン', example_meaning = 'gourd' WHERE character = 'ヒョ';
UPDATE katakana_characters SET meaning = 'mya', example_word = 'ミャンマー', example_meaning = 'Myanmar' WHERE character = 'ミャ';
UPDATE katakana_characters SET meaning = 'myu', example_word = 'ミュータント', example_meaning = 'mutant' WHERE character = 'ミュ';
UPDATE katakana_characters SET meaning = 'myo', example_word = 'ミョー', example_meaning = 'myo (French)' WHERE character = 'ミョ';
UPDATE katakana_characters SET meaning = 'rya', example_word = 'リャン', example_meaning = 'liang (currency)' WHERE character = 'リャ';
UPDATE katakana_characters SET meaning = 'ryu', example_word = 'リュック', example_meaning = 'rucksack' WHERE character = 'リュ';
UPDATE katakana_characters SET meaning = 'ryo', example_word = 'リョウ', example_meaning = 'ryo' WHERE character = 'リョ';
UPDATE katakana_characters SET meaning = 'gya', example_word = 'ギャング', example_meaning = 'gang' WHERE character = 'ギャ';
UPDATE katakana_characters SET meaning = 'gyu', example_word = 'ギュウニュウ', example_meaning = 'gyu nyu' WHERE character = 'ギュ';
UPDATE katakana_characters SET meaning = 'gyo', example_word = 'ギョウ', example_meaning = 'profession' WHERE character = 'ギョ';
UPDATE katakana_characters SET meaning = 'ja', example_word = 'ジャケット', example_meaning = 'jacket' WHERE character = 'ジャ';
UPDATE katakana_characters SET meaning = 'ju', example_word = 'ジュース', example_meaning = 'juice' WHERE character = 'ジュ';
UPDATE katakana_characters SET meaning = 'jo', example_word = 'ジョン', example_meaning = 'John' WHERE character = 'ジョ';
UPDATE katakana_characters SET meaning = 'bya', example_word = 'ビャラ', example_meaning = 'villa' WHERE character = 'ビャ';
UPDATE katakana_characters SET meaning = 'byu', example_word = 'ビュロー', example_meaning = 'bureau' WHERE character = 'ビュ';
UPDATE katakana_characters SET meaning = 'byo', example_word = 'ビョウ', example_meaning = 'biyo' WHERE character = 'ビョ';
UPDATE katakana_characters SET meaning = 'pya', example_word = 'ピャラ', example_meaning = 'pyala' WHERE character = 'ピャ';
UPDATE katakana_characters SET meaning = 'pyu', example_word = 'ピュア', example_meaning = 'pure' WHERE character = 'ピュ';
UPDATE katakana_characters SET meaning = 'pyo', example_word = 'ピョウ', example_meaning = 'pyo' WHERE character = 'ピョ';